### ISSUE TITLE
Microservice для обработки ссылок (пакетной)

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#100]
@maximsheiko детализируй таску для @serhii-kcrzko 

http://aws.amazon.com/documentation/lambda/

**Comment by maximsheiko** [comment]
вот код самого поиска: https://github.com/startup-erector/website/blob/master/server/methods.js#L164-L216
вот код поиска по гуглу: https://github.com/startup-erector/website/blob/master/server/methods.js#L121-L157
нужно реализовать функцию выдачи результатов гугла массивами по 50 ссылок, и так же входящий параметр поиска по комментах - массив.
результат работы - тоже массив со ссылками в которых можно размещать комментарии
