### ISSUE TITLE
Подготовить текст страницы privacy policy.

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#103]
У нас сейчас нет политики конфиденциальности, нужно написать что то типичное для таких проектов. Можно посмотреть какие это реализовано у других сайтов что предоставляют похожие услуги.

**Comment by orestx** [comment]
@maximsheiko Сделай публичную страницу с этим текстом (но что бы было наше меню, в общем как страница сайта).
Url сделай какой то типа http://startup-erector.com/privacy_policy. И вложи сюда ссылку на эту страницу.

------------------------------


<h3>Our commitment to data security.</h3>

<p>Secure the safety of your personal data is a prerequisite. Startup-Erector - application aimed at finding and analysis of third-party web resources, and does not require any large amount of personal information. Nevertheless, to create your account and for ease of use of our application, we need to receive some information from you and store this on our servers.</p>

<h3>The types of information we collect</h3>

<p>Such data includes: name and email address. Also, while using the application, we store information such as the address of your web site, or names that you assign your campaigns. Also on our servers, while user adds (if any), message templates are stored, used for writing comments on web pages that our application found. And also we can capture your mouse movements on our website and analyze this information in order to enchance ease of use of our product.</p>
<p>The other information that is automatically detected, include your IP-address, browser and operating system version.</p>

<h3>Using your Information</h3>

<p>We do not oblige you to provide us with personal information, your consent - voluntary. But without this information we can not provide you with our services and you will not be able to use our application. Collected information is stored on our servers and is unavailable for public viewing. We will never rent or sell any personally identifiable information to a third party unless required to provide a service requested and agreed to by you. We reserve the right to disclose personal information as required by law.</p>

<h3>Change of personal data</h3>
<p>You can correct errors and modify your personal data. To do this, go to the website and edit the information.</p>

<h3>Cookies</h3>

<p>Cookies are small text files sent through your browser and saved in your hard drive. TimeDoctor.com uses cookies to uniquely identify you and save the preferences you set from your previous visit into the site. You may choose to disable cookies by selecting this option on your browser. Disabling cookies may, however, disable some services activated using such technology.</p>

<h3>Still have questions?</h3>

<p>If after reading this document, you still have doubts or questions, please <a href="mailto:info@startup-erector.com">contact us</a>.</p>

**Comment by maximsheiko** [comment]
http://startup-erector.com/privacyPolicy сделал

**Comment by orestx** [comment]
ок
