### ISSUE TITLE
Если активировать больше кампаний чем разрешено тарифом, визуально они активируются

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#105]
Но похоже что это только визуальный глюк, потому что при перезагрузке страницы лишние кампании оказываются отключенными, получается в базу это не пишется.

**Comment by alexzaporozhets** [comment]
@maximsheiko прокомментируй, как ты хотел его починить

**Comment by maximsheiko** [comment]
там стоит условие на запись в базу, добавить к нему что то вроде this.$('active')[0].cheked = false

**Comment by orestx** [comment]
Работает, только для кого тут логирование?
![image](https://cloud.githubusercontent.com/assets/2162824/8645084/fad07e7c-294c-11e5-9906-bee513be792e.png)

**Comment by vladmokryi** [comment]
@orestx оно было до того как я правил код, я и не трогал

**Comment by orestx** [comment]
Хорошо, но убери это.

**Comment by orestx** [comment]
ok
