### ISSUE TITLE
Пустое поле на странице редактирования компании

### ISSUE THREAD

**Issue by vladmokryi** [startup-erector/website#106]
Скорей всего это поле веб-сайта
![image](https://cloud.githubusercontent.com/assets/13148141/8548815/c5286450-24cf-11e5-9799-0945b9a1edc7.png)

**Comment by orestx** [comment]
@vladmokryi 
У тебя еще есть такие (безимянные) кампании? Макс кажется делал миграцию что бы их не было ни у кого. Если уже нет то можешь закрывать issue.
