### ISSUE TITLE
Infinite scroll on the scanpage

### ISSUE THREAD

**Issue by maximsheiko** [startup-erector/website#107]
сделать бесконечную подгрузку строк по примеру 
https://github.com/aslagle/reactive-table/issues/73

**Comment by orestx** [comment]
Вродь оно. Только хорошо бы добавить какой то элемент в конце таблицы, что бы было понятно что докрутил до конца. Пока нет идей как именно он должен выглядеть.

**Comment by vladmokryi** [comment]
@orestx возможно блок по ширине таблицы с надписью "Наверх"

**Comment by orestx** [comment]
Я вообще хотел бы кнопку "наверх", которая будет раньше конца появляться. Потому что иногда элементов очень много. А там можна футер вставлять. Раз не можем наживо его переносить то можно сделать что бы в конце, когда долистываешь - появлялся. Или еще что..
@alexzaporozhets @chemfind у вас нет мыслей по этому поводу?

**Comment by vladmokryi** [comment]
#126

**Comment by orestx** [comment]
Главное что я хотел в этой теме это не кнопка наверх(она сделана в #126). Как быть с индикацией окончания таблицы? Давайте хотя бы отступ побольше от конца сделаем.
![image](https://cloud.githubusercontent.com/assets/2162824/8980232/b314408c-36b7-11e5-92c6-22446b701b0d.png)

**Comment by orestx** [comment]
Проблема с индикацией окончания решена..
![image](https://cloud.githubusercontent.com/assets/2162824/12511985/19fcaac8-c11e-11e5-9e4f-a1f268a8838f.png)
Закрываю задачу
