### ISSUE TITLE
Новый баг с избранным

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#117]
1. Перейти на страницу списка лидов.
2. Отключить/Включить фильтром одну из поисковых систем (главное ткнуть тот фильтр).
3. Нажать на сортировку по избранному.
4. Нажать на звездочки, пытаясь добавить некоторые записи в избранное. Но визуально ничего не будет происходить, мы не увидим что бы записи добавлялись в избранное. Хотя на самом деле они добавляются, только визуально мы этого не видим.

**Comment by vladmokryi** [comment]
Вспомнил что в reactive table можно написать кастомные фильтры
вот перевел все фильтры что были, визуально все осталось так же

**Comment by orestx** [comment]
Вродь все работает, гуд.
