### ISSUE TITLE
Хранить настройки фильтра для каждой кампании в метеор сессии

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#123]
Session -> campaignsFilterSettings -> {ID}  = {}

**Comment by orestx** [comment]
Норм, но эти вкладки:
![image](https://cloud.githubusercontent.com/assets/2162824/8980766/d0832774-36bb-11e5-9471-88369aecb76c.png)
Тут думаю тоже нужно запоминать для каждой кампании отдельно, или не запоминать вообще.
@alexzaporozhets что скажешь?

**Comment by alexzaporozhets** [comment]
@orestx для каждой компании отдельно 100%

**Comment by orestx** [comment]
Все еще запоминаем один раз для всех кампаний в учетной записи...

**Comment by orestx** [comment]
норм
