### ISSUE TITLE
Сделать триггер (breadcrumb) в заголовке 

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#124]
<img width="1044" alt="startup_erector__we_trigger_your_potential_clients_desires_" src="https://cloud.githubusercontent.com/assets/891472/8765638/d32e556c-2e1d-11e5-81ed-a5b8bdf6cca3.png">
http://semantic-ui.com/collections/breadcrumb.html

**Comment by orestx** [comment]
ok

**Comment by orestx** [comment]
или не ок!? Как так?? Почему не проверяешь уже который раз?
![image](https://cloud.githubusercontent.com/assets/2162824/8982617/cb2cf9de-36cb-11e5-8f18-2d5fa0ffb28d.png)

**Comment by maximsheiko** [comment]
https://isells.slack.com/archives/startup-erector/p1438095068000023
я писал об этом, и я не вижу простого решения, сейчас я просто строго ограничил количество символов = 50,но 50 букв О будут занимать большеместа чем 50 k

**Comment by orestx** [comment]
>я писал об этом

не вижу в этой задаче ни одного твоего коммента.
Напиши тогда в канале front-end, ведь "не знаю" это не значит что проблема устранена  и можно проверять. Мы уже такое проходили.
