### ISSUE TITLE
Убрать отдельную линию для Country

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#125]
<img width="1106" alt="startup_erector__we_trigger_your_potential_clients_desires_" src="https://cloud.githubusercontent.com/assets/891472/8765642/03a9494a-2e1e-11e5-9df2-a79f5a009377.png">

**Comment by orestx** [comment]
Сделай слева от флажка отступ 5px:
![image](https://cloud.githubusercontent.com/assets/2162824/8951823/dd262af4-35d9-11e5-951b-020ab437adbe.png)


@alexzaporozhets 
Теперь тут стало пустое пространство во время сканирования (нужно что то придумать, что с этим сделать):
![image](https://cloud.githubusercontent.com/assets/2162824/8951557/85c952ba-35d7-11e5-997d-03c281890de2.png)

![image](https://cloud.githubusercontent.com/assets/2162824/8951753/1d6b86fa-35d9-11e5-9d93-fced4f8015dd.png)

Может какой то текст написать, типа подождите пожалуйста, мы обнюхиваем для вас интернет в поисках того что вы заказали.

**Comment by alexzaporozhets** [comment]
А может его по центру сделать? и  после выполнения он просто исчезнет

**Comment by orestx** [comment]
ок, так и сделаем

**Comment by vladmokryi** [comment]
@alexzaporozhets @orestx 
а может растянуть?

**Comment by orestx** [comment]
Если растянуть получится так:
![image](https://cloud.githubusercontent.com/assets/2162824/9001942/ad8b22a2-3766-11e5-900b-ce72703c4d7d.png)

А вот не растягивая:
![image](https://cloud.githubusercontent.com/assets/2162824/9002260/5a4ac83c-376a-11e5-8207-47abdfc91677.png)

Только не пойму, почему я занимаюсь визуализацией ваших идей..

**Comment by orestx** [comment]
Оба варианта нормально смотрятся, но на всю ширину кажется лучше, хотя еще можно так, что тоже не плохо:

![image](https://cloud.githubusercontent.com/assets/2162824/9002428/ba7855c4-376c-11e5-8f46-280efd78c062.png)

**Comment by alexzaporozhets** [comment]
давайте попробуем на всю ширину оставить

**Comment by orestx** [comment]
ок
