### ISSUE TITLE
Нужно проверить все страницы, что бы не было возможности подгружать страницы других пользователей 

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#128]
Например http://www.startup-erector.com/scans/edit/fuyZvMb6uKKarcNrj

**Comment by orestx** [comment]
Почему незарегистрированный посетитель видит блок Current plan? Почему он free user если он пока никакой не юзер? А доступные планы хз, может пусть  и будут..

![image](https://cloud.githubusercontent.com/assets/2162824/8951503/19724252-35d7-11e5-9bb0-f6ad7f16454f.png)

**Comment by maximsheiko** [comment]
Ну я думаю пользователь должен иметь возможность просматривать тарифы до регистрации, может ссылку какую то добавить на стартовую, предлагаю обсудить

**Comment by orestx** [comment]
Прочитай еще раз то что я написал.
У незарегистрированного посетителя не должно писать какой у него сейчас тариф так как тарифа у него нет никакого. Даже обрезанного, потому что он даже не зарегистрирован.

**Comment by maximsheiko** [comment]
ну насчет этого я понял, уберу

**Comment by maximsheiko** [comment]
исправил

**Comment by orestx** [comment]
На чей счет пойдут мои БТК если я не зарегистрирован??
![image](https://cloud.githubusercontent.com/assets/2162824/8982202/93105df6-36c7-11e5-890f-ced2c7a9c449.png)

**Comment by orestx** [comment]
Еще такой маленький нюансик.
При переходе на страницу http://www.startup-erector.com/settings, будучи не зарегистрированным, я увидел что на миг прорысовывается страница настроек а только потом меня перекидывает на стартовую.
Если к тебе придет какой то "левый мужик" и попросит у тебя пароль от сейфа. Ты сначала принесешь ему на бумажке пароль а потом попытаешься выдернуть у него с рук эту бумажку (даже если у тебя это шустро получается) и молча унесешь ее домой? Или со старта скажешь ему пнх?
Твой вариант реализации сначала отдает запрещенную страницу а потом пытается быстро забрать ее у посетителя и всунуть вместо нее стартовую.

![image](https://cloud.githubusercontent.com/assets/2162824/8982348/095f9caa-36c9-11e5-88a1-e8b8bb2e60c3.png)
https://slack-files.com/T0271DLHB-F08C90212-fd9c992d26

**Comment by maximsheiko** [comment]
вроде исправил

**Comment by orestx** [comment]
В общем хз, визуально не видно, но коды ответа не правильные. Но этот вопрос поднимался в другой задаче, так что эту закрываю
