### ISSUE TITLE
Обработка запрета на отображение найденного сайта в фрейме.

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#13]
Когда я перехожу на сайт, у которого стоит запрет на отображение в iframe, у нас я просто ничего не вижу. Нужно давать какое то сообщение, что мол такое дело, вот ссылка, по нажатию откроется этот сайт в новой вкладке (или как мы решили обходить этот запрет?). 
http://storage1.static.itmages.com/i/15/0407/h_1428393173_6611170_60d7720186.png

**Comment by orestx** [comment]
Не работает. Вот пример сайта, который не дает отображать себя в фрейме:
http://baraxolka.com.ua/marketing/mystery-shopper-detail.html
Перекидывает на их сайт.

**Comment by maximsheiko** [comment]
хм...я обрабатываю только сайты с x-frame,а там стоит что то другое..надо в их кодах копаться

**Comment by vladmokryi** [comment]
обработку перенесли на сервис @serhii-kcrzko 
по этой ссылке у нас будет сообщение "открыть в новом окне"

**Comment by orestx** [comment]
ок
