### ISSUE TITLE
при больших полях keywords и когда три соцсети у одного лида - есть опасность бага с таблицей

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#130]
![image](https://cloud.githubusercontent.com/assets/2162824/8924704/f7c70a8a-3508-11e5-8a46-6343c60afc53.png)

![image](https://cloud.githubusercontent.com/assets/2162824/8924709/01c60bda-3509-11e5-8967-240dd860ecf4.png)

**Comment by maximsheiko** [comment]
![image](https://cloud.githubusercontent.com/assets/10918691/8925688/7c5e9494-3512-11e5-9c34-c2084f00edec.png)
не могу воспроизвести баг

**Comment by orestx** [comment]
ок
