### ISSUE TITLE
удаление сайтов конкурентов багнутое

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#133]
Когда я удаляю верхний сайт конкурента, удаляются данные с нижнего. То есть жму на крестик гугла но удаляется яндекс а гугл остается
![image](https://cloud.githubusercontent.com/assets/2162824/8981797/c180d8fe-36c3-11e5-9794-63bacb6317f8.png)

**Comment by maximsheiko** [comment]
исправил

**Comment by orestx** [comment]
ok
