### ISSUE TITLE
Время до окончания сканирования не помещается в своей клетке

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#134]
![image](https://cloud.githubusercontent.com/assets/2162824/9002359/a1295434-376b-11e5-8339-a2806c481e1b.png)

**Comment by alexzaporozhets** [comment]
End in можно заменить на ETA

**Comment by orestx** [comment]
При этом ты сознательно откусил одну единицу ширины, сломав симетричность верстки (справа пустота размером 1/16):
![image](https://cloud.githubusercontent.com/assets/2162824/9002391/4b8dcfea-376c-11e5-8f29-03979f663d35.png)

**Comment by orestx** [comment]
![image](https://cloud.githubusercontent.com/assets/2162824/9628760/3966ceec-5176-11e5-9c92-c093c6606e8c.png)

Так и планировалось что время на таймере заморожено и меняется только когда меняется % прогресса на шкале?
@alexzaporozhets @maximsheiko

**Comment by maximsheiko** [comment]
ну тут 2 варианта - либо отображать приблизительное, но динамичное время, либо точное но с рывками
