### ISSUE TITLE
Тариф всегда заканчивается в полночь

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#139]
![image](https://cloud.githubusercontent.com/assets/2162824/9031871/56d30b0c-39c1-11e5-91e1-11589127ea35.png)

**Comment by orestx** [comment]
при этом не нужно эту полночь указывать. Просто не писать время, типа: "Заканчивается 3 августа 2015 года" вместо "Заканчивается 3 августа 2015 года в 11:00"

Правда, наверное у тебя возникнет вопрос, по какому часовому поясу должна быть полночь.. Мы этот вопрос поднимали но похоже что не записали, в общем не могу вспомнить итог. Сейчас учтоним...

**Comment by orestx** [comment]
Не предусмотрено обработку такой мелочи, как ситуации когда время действия тарифа закончилось.
![image](https://cloud.githubusercontent.com/assets/2162824/9083801/030af7a8-3b76-11e5-84aa-c941c0492bae.png)

**Comment by orestx** [comment]
И как понимать эту надпись?
![image](https://cloud.githubusercontent.com/assets/2162824/9847416/5bbdede4-5ae1-11e5-9e9e-8567c8883c26.png)

**Comment by vladmokryi** [comment]
добавлен крон на проверку, запускается 1 раз в день через 5 мин после рассылки писем

**Comment by orestx** [comment]
Текст очень близко к шапке. Не хватает дивайдера с текстом. Думаю годится даже тот что был при активном тарифе, тоесть "CURRENT PLAN"
![image](https://cloud.githubusercontent.com/assets/2162824/12451668/4dd40580-bf93-11e5-9ca1-4951745c878a.png)

**Comment by orestx** [comment]
А, сори. Это у меня почему то не догрузилось, а так - после перезагрузки страницы стало норм.
