### ISSUE TITLE
IE-bug: Проблемы со ссылками/кнопками в internet explorer 11

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#144]
Жму upgrade, а меня перекидывает на dashboard:
![image](https://cloud.githubusercontent.com/assets/2162824/9163006/d341a7f4-3f50-11e5-8be8-30d69be1316e.png)

Выбираю i don't have a website, сначала вроде бы сработало, но потом, через 1 секунду перекидывает на dashboard:
![image](https://cloud.githubusercontent.com/assets/2162824/9163069/28955f20-3f51-11e5-8406-295b2e98f10a.png)

Жму add competitor url - тоже самое, кидает на dashboard.

Нажал анализировать url - баг который мы уже фиксили, зависло (хотя повторно все сработало норм, хз почему зависало), и иногда нормально ищет а иногда зависает.

**Comment by maximsheiko** [comment]
убрал все пустые ссылки, заменил их span со стилем ссылки
