### ISSUE TITLE
Пошук по вк 

### ISSUE THREAD

**Issue by Iryna-Ivasko** [startup-erector/website#158]
![image](https://cloud.githubusercontent.com/assets/12249275/9403227/cc0689dc-47ed-11e5-96de-3d7301f9d031.png)
Взагалі не працює пошук по вк

**Comment by serhii-kcrzko** [comment]
More details, please. Не знаходяться посилання взагалі, чи по кліку на всі лінки з’являється один і той же опус Паші Дурова?

**Comment by Iryna-Ivasko** [comment]
Постійно нас вітає Паша, як на скріні

**Comment by maximsheiko** [comment]
убрал пост Паши
