### ISSUE TITLE
Проверка на дубликаты Сообщений (комментариев)

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#16]
Нужна проверка на дубликаты, если вы пытаюсь добавить одно и то же сообщение, выдавать подсказку что оно уже есть и не разрешать добавление. 
http://storage4.static.itmages.com/i/15/0407/h_1428390453_7289266_10422c5c63.png

**Comment by orestx** [comment]
Хорошо но не до конца.

Анализируем скрин:
![image](https://cloud.githubusercontent.com/assets/2162824/7347004/ac12654e-ecec-11e4-8a77-093915fc8007.png)

То что выделенно - идентичны сообщения. Как? Легко. Добавил дубликат, но с доп символом. Потом открыл его на редктирование и удалил лишний символ. После чего успешно сохранил и очень удивился когда увидел что такое сообщение у меня уже есть. В общем нет проверки при редактировании. Предлагаю в случае дубликата писать "Такое сообщение уже есть, удалить это "цитируем сообщение", как дубликат уже существующего или продолжить его редактирование?" кнопки Удалить/Продолжить


По поводу подчеркнутого красной линией. У меня там три абзаца. В таблице нужно их так же отображать. Можешь посмотреть, на старом http://social-bot.herokuapp.com оно так сделано.

**Comment by maximsheiko** [comment]
>Предлагаю в случае дубликата писать
идея хорошая,но реализовать не получилось,так как richsilv/semantic-ui-modal,который я использую почему то не позволяет работать с множественными модальными окнами,поэтому сделал такую же валидацию как и на добавление комента

**Comment by orestx** [comment]
Блин, ну что это такое? Второе сделал, но первое сломал? Это я добавил без редактирования, просто добавлял новые сообщения:
![image](https://cloud.githubusercontent.com/assets/2162824/7390562/3addc5f2-ee82-11e4-89af-4e4353bc8182.png)

А вот это после того как я отредактировал коммент и нажал в модальном окне "ок":
![image](https://cloud.githubusercontent.com/assets/2162824/7390600/86b00b0c-ee82-11e4-9816-27e2111692a7.png)
 Вообще кампания накрылась медным тазом. Выхожу на dashboard и возвращаюсь в эту кампанию и вижу ту же картинку(пустой экран).

**Comment by orestx** [comment]
То что на скринах - манипуляции со старой кампанией. Создал новую - то же самое, нет проверки и после редактирования накрылась

**Comment by orestx** [comment]
Сейчас копию не добавляет, выдет ошибку - гуд.

Добавляю комментарий с новой строкой в конце:
![image](https://cloud.githubusercontent.com/assets/2162824/7794045/fbc72fbe-02ce-11e5-9a56-312b2ee397c0.png)
и открываю его на редактирование - вижу вместо новой строки - запятая:
![image](https://cloud.githubusercontent.com/assets/2162824/7794065/1f4dd474-02cf-11e5-8fee-2cdfcf5798ce.png)
сохраняю с этой запятой - вижу ошибку что такое есть(хотя там было с новой строкой). Добавляю еще одну новую строку и смотрю что сохранилось:
![image](https://cloud.githubusercontent.com/assets/2162824/7794078/432a7956-02cf-11e5-89bd-383252cef13a.png)
Открываю эту запятую с новой строкой на редактирование - вижу уже две запятых:
![image](https://cloud.githubusercontent.com/assets/2162824/7794087/4f54a4b8-02cf-11e5-9666-bece135b3400.png)

**Comment by orestx** [comment]
Правлю второй коммент все время, а мне пишет что второй от создания не правился, зато первый, который бил создан и все - правился по твоей версии несколько секунд назад:
![image](https://cloud.githubusercontent.com/assets/2162824/7794159/139f2dd4-02d0-11e5-96b4-4dbea59e868b.png)

**Comment by orestx** [comment]
после и того как я обновил страницу в браузере, то дата первого коммента обновилась и стало вродь норм. Но перед этим я удалил коммент который все время правил поэтому не знаю как бы он себя повел.
Но.
Я еще раз добавил коммент и отредактировал его. Тогда обнаружилось что с момента правки коммента дата не меняется. Пробовал уже и обновлять станицу но безрезультатно, modified считает от момента создания.

**Comment by maximsheiko** [comment]
исправил

**Comment by orestx** [comment]
Modified стало норм считать. А как насчет того что новые строки при редактировании заменяются запятыми?

**Comment by orestx** [comment]
гуд
