### ISSUE TITLE
Проблема з відобреженням заголовків та контенту сайту

### ISSUE THREAD

**Issue by Iryna-Ivasko** [startup-erector/website#169]
![image](https://cloud.githubusercontent.com/assets/12249275/9576149/d47f2c70-4fdd-11e5-9a69-526794e4cd11.png)
думаю, ця проблема пов'язана з #168

**Comment by serhii-kcrzko** [comment]
Ноуп, ця проблема пов’язана з тим, що у чуваків якесь упороте кодування. 
Дай, позязя, ще однин приклад такої красоти.

**Comment by Iryna-Ivasko** [comment]
В нас таких штук побільшало, неможливо працювати. майже через кожен лід
![image](https://cloud.githubusercontent.com/assets/12249275/9608495/515a1422-50d7-11e5-9163-6d67478b7a0d.png)
