### ISSUE TITLE
Накладання панелей при відкритті лідів

### ISSUE THREAD

**Issue by Iryna-Ivasko** [startup-erector/website#171]
![image](https://cloud.githubusercontent.com/assets/12249275/9610575/196cad52-50e3-11e5-93af-899d1aceb2f6.png)
Частенько відбувається такий баг (закономірність його появи пока виявити не вдалось)

**Comment by maximsheiko** [comment]
Это старый скрин, сейчас поля Admin page нету, думаю это с ним был связан баг, сделай такой же скрин сейчас

**Comment by Iryna-Ivasko** [comment]
![image](https://cloud.githubusercontent.com/assets/12249275/9611388/08646518-50e8-11e5-9045-e93b76055939.png)
щойно зробила
