### ISSUE TITLE
Повернення та поточне місце в таблиці

### ISSUE THREAD

**Issue by Iryna-Ivasko** [startup-erector/website#173]
При переході на лід і назад, не правильно визначається моє поточне місце в таблиці(на яке повинно повертати)(в відео скрол не використовую)http://www.screencast.com/users/Iryna.Ivasko/folders/Startup-erector/media/f1e6e099-4374-4650-b519-273bf12d77cf

**Comment by orestx** [comment]
Это уже не актуально, так как мы используем модальное окно вместо перехода на страницу лида.
