### ISSUE TITLE
Обновление при сканировании статуса лида

### ISSUE THREAD

**Issue by Iryna-Ivasko** [startup-erector/website#176]
При новых сканированиях он выдает ссылки, которые уже были ранее (то есть они повторяются) + там уже наши посты.(это очень часозатратно: просматривать тритину лидов из всех, а там уже запощено). Нужно убрать обновление статуса при сканировании.

**Comment by orestx** [comment]
@maximsheiko на проверку на того кто создавал задачу, если это не особый случай.
