### ISSUE TITLE
Добавить текстовый поиск по сообщениям

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#18]
Нужно добавить текстовый поиск по сообщениям.. Когда их много, было бы удобнее их таким образом фильтровать, например разместив его под вкладками Links, Comments, Stats: 
http://storage2.static.itmages.com/i/15/0407/h_1428390694_5580389_88c6e350f9.png

**Comment by vladmokryi** [comment]
Интерфейс поменялся, не актуально
