### ISSUE TITLE
В сообщениях, в шапке таблицы не хватает выравнивания по центру

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#19]
http://storage2.static.itmages.com/i/15/0407/h_1428390757_7512223_a008735aa7.png

**Comment by orestx** [comment]
Что то мне больше нравится когда actions были каждый в своей ячейке, а не в одной как сейчас
![image](https://cloud.githubusercontent.com/assets/2162824/7065515/3d82fabe-dec1-11e4-96b6-ecd5ea1ccecc.png)
Предлагаю это обсудить.

Кроме этого. В любом случае, нужно что бы графа "текст" имела преимущество по ширине перед остальными. Для actions вообще никогда ширина не меняется, там всегда один набор иконок. Можно ее сделать уже. Насчет даты не знаю, можно сделать уже но потестировать что бы все варианты помещались, можно попробовать не трогать ее.

**Comment by alexzaporozhets** [comment]
@maximsheiko ты неправильно меня понял, копировать нужно оставить в отдельной колонке

**Comment by orestx** [comment]
Изменений по ширине, о которых я писал, не сделано.

**Comment by orestx** [comment]
Ай молодец, порадовал старичка :D
