### ISSUE TITLE
На админской странице баг с кнопкой отмены

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#192]
При попытке нажать "Cancel", на окне подтверждения удаления пользователя - ничего не происходит:
![image](https://cloud.githubusercontent.com/assets/2162824/10868653/ddfceac2-809c-11e5-9430-b37dff36c735.png)

**Comment by orestx** [comment]
Кажется дело не только в админской странице, удаление комментария так же само себя ведет - кнопка отмены не реагирует. Получается проблема глобальная:
![image](https://cloud.githubusercontent.com/assets/2162824/10868767/2cf0d70c-80a1-11e5-9f83-9b90b4ce50d7.png)

**Comment by vladmokryi** [comment]
исправил

**Comment by orestx** [comment]
ok
