### ISSUE TITLE
Title для счетчика публикаций, которые находятся в статусе "New"

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#194]
Раньше тут было два показателя, всего кампаний, и новых. Теперь же, когда осталось одно число. Стоит более понятно написать что это за такое "New". Что то типа "Number of the new publications".
![image](https://cloud.githubusercontent.com/assets/2162824/10868678/ee46229e-809d-11e5-8880-78a80d138c83.png)

**Comment by vladmokryi** [comment]
Добавил

**Comment by orestx** [comment]
good
