### ISSUE TITLE
Неудачное размещение кнопки для удаления лидов по ключевому слову

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#196]
У меня есть сомнение что кнопка удаления всех лидов по ключевику должна находиться там где меняется статус конкретного лида:
![image](https://cloud.githubusercontent.com/assets/2162824/10868726/0005eda0-80a0-11e5-8c04-b703c1501794.png)

Зато не вижу такой кнопки на странице просмотра лида:
![image](https://cloud.githubusercontent.com/assets/2162824/10868741/47b51090-80a0-11e5-8459-6081e8d350a2.png)

Не понимаю, как работает счетчик:
![image](https://cloud.githubusercontent.com/assets/2162824/10868720/ca06e574-809f-11e5-8def-f50b960f4830.png)

**Comment by vladmokryi** [comment]
исправил

**Comment by vladmokryi** [comment]
блок по ключу перенесли
![image](https://cloud.githubusercontent.com/assets/13148141/11000722/08e7f19c-84ac-11e5-9289-8a136f052dbf.png)

**Comment by orestx** [comment]
Счетчик заработал, ок. И перенесли кнопку, тоже хорошо. Но еще пару замечаний:
Нужно хотя бы title="Remove keyword" и title="Hide keyword" соответственно (Можете с @serhii-kcrzko посоветоваться, мож текст лучше какой то придумаете.. http://prntscr.com/93cnvw )

**Comment by vladmokryi** [comment]
![image](https://cloud.githubusercontent.com/assets/13148141/11241726/d613ba18-8e05-11e5-9cf2-e2f20da358b1.png)

**Comment by orestx** [comment]
Гуд, намного лучше.
Но есть еще нюанс))

Когда жму удалить ключевик
![image](https://cloud.githubusercontent.com/assets/2162824/11334859/8d9cced0-91e0-11e5-964d-a5f9d39d9cba.png)

в окне что появилось, я не могу переключиться на вкладку удаления канала:
![image](https://cloud.githubusercontent.com/assets/2162824/11334863/93a09b72-91e0-11e5-86bc-497c52f854f1.png)

Как я понял, печатая это сообщение, дело в том, что удаляя канал, мы знаем какой ключевик с ним связан, так как кликаем на конкретном лиде; а вот удаляя ключевик, мы не знаем какой канал пользователь хотел бы удалить. Но если так, хорошо бы эту вкладку как то изображать так, что бы было сразу понятно что это не баг, а она отключена. Или высветлить ее, или еще какое то решение.. Потому что сейчас, неактивная вкладка, на которую можна кликать:
![image](https://cloud.githubusercontent.com/assets/2162824/11334967/45892ec6-91e1-11e5-8388-34c1d1a6be2a.png)
ничем не отличается от той что заблокоированная:
![image](https://cloud.githubusercontent.com/assets/2162824/11334991/64991358-91e1-11e5-9fd3-9045e6297ece.png)

**Comment by vladmokryi** [comment]
Это не баг, я так и делал
Ок, подумаю как выделить

**Comment by orestx** [comment]
о, норм
