### ISSUE TITLE
Новогоднее украшение лэндинга

### ISSUE THREAD

**Issue by chemfind** [startup-erector/website#205]
а мы сможем прикрепить шапку Санты нашему чувачку? )
![startup_erector___social_media_monitoring__lead_generation_and_comments_services](https://cloud.githubusercontent.com/assets/7547101/11973691/67c23b22-a965-11e5-93bc-23a9a0057ee0.jpg)

**Comment by chemfind** [comment]
для социалок прозрачные png чувачка в шапке от 600
если композиция с елкой: 1500х1500

**Comment by alexzaporozhets** [comment]
@chemfind уверен что 1500х1500? такая рартинка не влезет на монитор ноутбука или социалки ее смаи маштабируют?

**Comment by alexzaporozhets** [comment]
http://hi-tech.ua/article/shparshalka-po-razmeram-kartinok-dlya-sotsialnyih-setey/

Еще актуально?

**Comment by alexzaporozhets** [comment]
![all_2](https://cloud.githubusercontent.com/assets/891472/11981750/0ee4ef24-a9ae-11e5-8c80-cac543575969.jpg)
![all](https://cloud.githubusercontent.com/assets/891472/11981749/0edff1ea-a9ae-11e5-947c-95e96659e110.jpg)

Какой вариант брать за основу?

**Comment by alexzaporozhets** [comment]
![12_try fw](https://cloud.githubusercontent.com/assets/891472/11981774/546c2bfc-a9ae-11e5-96c2-ac704701c1b9.png)
