### ISSUE TITLE
Нужно выравнивание по центру на странице ссылок

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#21]
http://storage4.static.itmages.com/i/15/0407/h_1428391107_8203630_c0059d49eb.png

**Comment by orestx** [comment]
Не вижу изменений
![image](https://cloud.githubusercontent.com/assets/2162824/7065428/52adf642-dec0-11e4-95aa-cabc873ec3a1.png)

Выравнивание для Keywords и Page думаю стоит обсудить. А выделенные желтым - делай по центру.

**Comment by maximsheiko** [comment]
там рядом с надписью скрытая иконка сортировки,а сам загловок сортирован по центру

**Comment by orestx** [comment]
@alexzaporozhets  предлагаю перебить стилями, попробовать что бы для .ui.sortable.table thead th:after стиль был display:none, а для .ui.sortable.table thead th.descending:after добавить display: inline:block;
Таким образом пока сортировка не юзается - не будет занимать место.
Потому что в случае с SE - вообще получается половина ширины занята невидимым полем.

**Comment by alexzaporozhets** [comment]
@orestx это сейчас не критично, давай перенесем в 3-й milestone (доработки после запуска)

**Comment by orestx** [comment]
ok
