### ISSUE TITLE
Нужна возможность удалять кампании

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#22]

**Comment by orestx** [comment]
>и уточнить что все данные связанные с ней будут потеряны

Сейчас такого нет
![image](https://cloud.githubusercontent.com/assets/2162824/7065207/e9fe4aae-debd-11e4-97a4-736ba39395fe.png)

**Comment by orestx** [comment]
По моему "related" больше подходит в нашей ситуации чем connected

![image](https://cloud.githubusercontent.com/assets/2162824/7065584/f123eb0a-dec1-11e4-9281-799710a68d51.png)

Предлагаю написать в скобках "All related data will be lost". И возможно скобки стоит убрать а написать просто следующим предложением.

**Comment by maximsheiko** [comment]
исправил

**Comment by orestx** [comment]
ok
