### ISSUE TITLE
Нужна возможность редактировать кампании

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#23]
Менять url, keywords, search engine, то есть видеть такую же страницу как при создании новой кампании, только там сразу должны быть заполнены те данные что сейчас есть, и кнопка должна просто сохранять не запуская новый скан.

**Comment by orestx** [comment]
Почему в одном месте кнопки управления все одного цвета а в другом разных? Нужно придерживаться какого то порядка.
![image](https://cloud.githubusercontent.com/assets/2162824/7064912/28ee36a0-debb-11e4-818b-851ff4971e61.png)
![image](https://cloud.githubusercontent.com/assets/2162824/7064953/9947e31a-debb-11e4-9ff3-95b698dfea25.png)


Я путем редактирования добавил еще одно ключевое слово, которое стало восьмым, но в таблице кампаний все ровно пишет семь:
![image](https://cloud.githubusercontent.com/assets/2162824/7064936/858f538a-debb-11e4-8a99-bcb11025f65d.png)

**Comment by maximsheiko** [comment]
fixed

**Comment by alexzaporozhets** [comment]
@orestx ?

**Comment by orestx** [comment]
При редактировании кампании должна быть проверка url как и при ее создании. Я смог легко сломать ссылку путем редактирования:

![image](https://cloud.githubusercontent.com/assets/2162824/7133669/5c3b06a0-e29e-11e4-8f9b-1f5310630185.png)

**Comment by maximsheiko** [comment]
1. regex настройки перенес
2. site.com.ua121sdfjnb - является верным форматом для regex,просто на запрос такого сайта будет выдаваться ошибка

**Comment by orestx** [comment]
@alexzaporozhets 
Вижу несколько вариантов:
- Поискать сервис что предоставляет возможность через API проверять существование домена.
- Проверят так же как и при создании кампании.
- Оставить как есть, так как это не критично. Стандартная проверка домена сейчас стоит.
- Что то еще
Вообще, по поводу доменов есть у меня одно замечание, но об этом в отдельной теме.
