### ISSUE TITLE
Вкладки для фильтрации ссылок по статусам

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#24]
На вкладке Links должна быть еще одна подгруппа вкладок, с помощью которых можно будет фильтровать ссылки по статусам. Тоесть что бы назывались New, Done, Canceled, All. По умолчанию ставить All, а потом запоминать на какой вкладке пользователь остановился и ее открывать при переходе на страницу ссылок. Например вкладки разместить праямо над табилцей, справа. 
http://storage2.static.itmages.com/i/15/0407/h_1428392067_1177916_39a8457b76.png

**Comment by orestx** [comment]
Неплохо,но не хватает одного момента. Когда я выхожу на dashboard а потом обратно захожу в эту кампанию, мне должна отображаться та вкладка, на которой я был когда выходил. Но это не критично, @alexzaporozhets , что скажешь? На старом мы такое делали, получается нужно..

**Comment by alexzaporozhets** [comment]
@orestx давай отдельной таской с low priority

**Comment by orestx** [comment]
ок
