### ISSUE TITLE
Сообщение о неправильном url должно быть в виде ошибки а не как ключевое слово.

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#28]
И возможно стоит поменять текст на что то типа "wrong url", но это в зависимости от механизма определения ошибки, так что разве что можно обсудить. Но сам способ отображения ошибки нужно поправить уже.
http://storage2.static.itmages.com/i/15/0407/h_1428400568_4322320_10fc7073ce.png

**Comment by alexzaporozhets** [comment]
![startup_erector__we_trigger_your_potential_clients_desires_](https://cloud.githubusercontent.com/assets/891472/7427149/c72c706a-efdd-11e4-9a8d-ee51ac5649de.png)
