### ISSUE TITLE
Нужна email-рассылка пользователям с новыми найденными ссылками.

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#32]
Желательно что бы была возможность выбирать опционально, каждый день или раз в неделю получать эту рассылку.

**Comment by alexzaporozhets** [comment]
В 10 утра по UTC [daily | weekly| off]

**Comment by orestx** [comment]
Предлагаю на народное обсуждение: @alexzaporozhets @chemfind @maximsheiko 
Во первых, частота рассылки уж точно не имеет никакого отношения к балансу. Кнопку баланс (и путь к странице тоже) нужно переименовать на что то другое. Если будем делать все настройки на одной странице, то назвать ее опции. Там, например разделено вкладками, будет тариф, настройки рассылки, возможность изменить пароль, email, имя.

Во вторых, как по мне, если рассматривать блок настройки рассылки там где он есть - смотрится очень убого. Если есть заголовок для рассылки, нужно что то и для тарифов, размер, положение... Нужно будет какой то нормальный макет всего этого.

В третьих. Почему у меня есть радиокнопка но ни один из пунктов не выделен? Он сломана и не работает? Ведь у этого переключателя всегда есть какое то положение. Если изначально рассылка отключена, поставь офф активным. Если дело в том что у новых кампаний так и будет, просто у старых не было этого параметра когда создавались, тогда для старых сделай обязательно миграцию и всем поставь тот параметр, который идет по умолчанию.

Так же на обсуждение, не кажется ли вам что на каждое такое изменение должно появляться сообщение, подтверждающее что настройки изменены? Не просто писать "Настройки изменены" а писать в таком формате: "Вы подписались на ежедневную рассылку новых найденных лидов". Кнопки сохранения у нас нет, так что мы можем легко делать оповещения по каждому изменению, и даже не можем, а нужно, что бы пользователь понимал что изменения сразу же вступили в силу, потому что сейчас выглядит как пустая, не рабочая форма.

**Comment by orestx** [comment]
Саму рассылку я активировал, завтра посмотрим придет ли что то

**Comment by orestx** [comment]
Блин, ничего не активировал. Обновляю страницу и вижу опять пустой радиобатон, похоже что данные не сохраняются. @maximsheiko ?

**Comment by maximsheiko** [comment]
данные сохраняются,но не отображаются, саму рассылку я активировал еще неделю назад,проверь ящик и спам - может туда что то приходило
насчет положения и убогости - просто сейчас нету страницы с полноценным редактированием профиля,потому засунул туда

**Comment by orestx** [comment]
ты активировал как раз в недлю или каждый день?

**Comment by maximsheiko** [comment]
по умолчанию пока не выключишь,стоит раз в день
проверь за 6,7 числа на gmail не приходило?

**Comment by orestx** [comment]
похоже что не было, не нахожу

**Comment by maximsheiko** [comment]
странно, ну ладно, давай день подождем, проверь плс gmail и обычную почту

**Comment by orestx** [comment]
не нахожу писем

**Comment by orestx** [comment]
Рассылка уже приходит. Но в письме я должен получать информацию  о том сколько новых лидов было найдено за период, указанный в опциях как интервал рассылки. И после этого можно доп. графой еще писать сколько всего новых (в таблице рассылки думаю лучше назвать их как необработанных, что бы не запутать пользователя) лидов. И если не было новых лидов, можно не присылать сообщение.

**Comment by orestx** [comment]
Еще я писал сделать всплывающее сообщение о том что частота рассылки изменена.

**Comment by orestx** [comment]
Если уже работает система, при которой письмо не отправляется, если не было найдено новых лидов (мне письма перестали приходить, значит заработала), добавь такую подсказку:
![image](https://cloud.githubusercontent.com/assets/2162824/8251190/164fd5f8-1683-11e5-9175-f1260ee601fe.png)

**Comment by alexzaporozhets** [comment]
Добавить тип отчета (w/d) и кол. новыйх лидов

**Comment by orestx** [comment]
Вродь норм
