### ISSUE TITLE
При удалении комментария из списка должно быть окно подтверждения

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#33]
Сейчас они просто удаляются "по нажатию на крестик", а нужно добавить что то такое:
![image](https://cloud.githubusercontent.com/assets/2162824/7063313/4650d57a-deae-11e4-9fe9-61cc16653af9.png)

Только на скрине сообщение в формате "Are you sure you want to remove this $message"
А нам нужно "Are you sure you want to remove this message?".  Или если вкладывать все сообщение в то окно, то вкладывать как то так:
"Are you sure you want to remove this message? 
<i>$message</i>"

**Comment by orestx** [comment]
@alexzaporozhets  Что скажешь,если тут в подтверждении написать просто "Remove this comment?" ? Что бы не было везде одно и то же сообщение на всех удалениях. Так как удалить сообщение не так важно как весь проект, то и в подтверждении можно спросить более легкой формой..

**Comment by alexzaporozhets** [comment]
:+1:

**Comment by orestx** [comment]
Только, Макс, почему заголовок у тебя remove scan? Поправь.
Кстати, @alexzaporozhets , сразу еще вариант - у нас везде идет (это видно на скрине к этой задаче) заголовок модального окна "Remove scan?" а в теле окна идет снова вопрос "Are you sure you want to remove this scan?".  Может в заголовке не спрашивать, а просто кратко описывать предназначение этого окна? тоесть писать не "Remove scan?" а "Scan removing", в случае комментариев header title:"Comment removing" + body: "Remove this comment?"
Или как там правильнее будет, "Remove comment" ? В этом плане хз как правильнее.

![image](https://cloud.githubusercontent.com/assets/2162824/7083339/1ddd9e28-df69-11e4-8a67-309371723fbe.png)

**Comment by orestx** [comment]
ок
