### ISSUE TITLE
Сайт должен отображаться в фрейме такой высоты, при которой не будет прокрутки на нашей странице

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#34]
![image](https://cloud.githubusercontent.com/assets/2162824/7063486/e10cf002-deaf-11e4-9a6e-197282be32f7.png)

**Comment by orestx** [comment]
@maximsheiko  разве что то поменялось?
![image](https://cloud.githubusercontent.com/assets/2162824/7131739/57e5c17a-e28b-11e4-9534-29428b373f89.png)

**Comment by maximsheiko** [comment]
![image](https://cloud.githubusercontent.com/assets/10918691/7131813/0a7aa440-e28c-11e4-91d3-c54442052c03.png)
cтранно,у меня все нормально,а с какого браузера вы тестируете?

**Comment by orestx** [comment]
Windows 8, chrome
Такие вещи нужно проверять сразу в нескольких браузерах.

**Comment by orestx** [comment]
У тебя монитор большой. Попробуй сделать высоту браузера 768px и посмотри на результат

**Comment by orestx** [comment]
о, теперь хорошо.
