### ISSUE TITLE
Зачем обрезать заголвоки найденных страниц и как лучше, что бы заголовок был ссылкой или url под ним?

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#35]
На новом сейчас:
![image](https://cloud.githubusercontent.com/assets/2162824/7064121/d3b00354-deb4-11e4-9202-f6e427a73884.png)

На старом приложении:
![image](https://cloud.githubusercontent.com/assets/2162824/7064192/47b58044-deb5-11e4-8139-8d0f938a9b88.png)

**Comment by maximsheiko** [comment]
Я вывожу tittle Через bing api, а оно их обрезает,вытаскивать напрямую с сайта целый title?

**Comment by orestx** [comment]
Думаю нет, это будет лишняя нагрузка. Я подумал это ты обрезаешь.

**Comment by alexzaporozhets** [comment]
@maximsheiko как на старом проекте, также текст ссылки нужно обвернуть в <small></small>

**Comment by alexzaporozhets** [comment]
@maximsheiko во время проверки страницы ты можешь получить title

**Comment by orestx** [comment]
Заголовки стали норм длины. Но, найди на скринах ниже отличия, которых не должно быть. Первый - в личном кабинете. Второй - когда я не зарегистрирован запускаю поиск.
![image](https://cloud.githubusercontent.com/assets/2162824/8301371/02c82290-1996-11e5-90e9-71e8acd492a7.png)

![image](https://cloud.githubusercontent.com/assets/2162824/8301378/0bfdbb04-1996-11e5-8d12-a6c8c781af7a.png)

В общем, в личном кабинете норм, а в публичной части - не видно изменений которые ты делал раньше, когда решили что ссылкой будет заголовок, а url под ним вложить в тэг <small>.

Так же, не понимаю, куда подевались статусы у некоторых лидов:
![image](https://cloud.githubusercontent.com/assets/2162824/8301494/e0cc29e2-1996-11e5-9bfd-a42c05ec9c46.png)

Если пролистать страницу ниже, которая на последнем скрине, то увидишь что все ссылки, которые не попали в скрин, получили статусы, проблемы только в верхних (а всего 108 ссылок найдено).

Кампания, которую я скринил - новая, только созданная. Никаких изменений, типа переключения статуса или сортировки, я не делал. Просто смотрел как сканирует..

**Comment by alexzaporozhets** [comment]
@chemfind ждет от тебя ответа

**Comment by maximsheiko** [comment]
насчет статусов, у меня не получилось повторить

**Comment by orestx** [comment]
у меня тоже не повторилось.
Ок
