### ISSUE TITLE
Нужно по аналогии со старым приложением, отображать сколько времени осталось до следующего запуска сканирования

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#36]
![image](https://cloud.githubusercontent.com/assets/2162824/7064331/872668f0-deb6-11e4-8638-55509690dc9e.png)

**Comment by orestx** [comment]
почти хорошо.

Как читать эту информацию?
![image](https://cloud.githubusercontent.com/assets/2162824/7980537/070d751a-0ab1-11e5-93c3-165466d4dc0b.png)

**Comment by orestx** [comment]
То что на скрине выше - на одной из отключенных кампаний, но не на всех. На части отключенных такое а на части из них - нормальное время. Только почему я вообще вижу сколько осталось до запуска сканирования у отключенных кампаний?
![image](https://cloud.githubusercontent.com/assets/2162824/7980644/d4f9e2ba-0ab1-11e5-8d01-dc3f487d1dcb.png)

**Comment by maximsheiko** [comment]
исправил

**Comment by orestx** [comment]
good
