### ISSUE TITLE
Нужна ли нам дата последней проверки в таблице-списке кампаний?

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#38]
![image](https://cloud.githubusercontent.com/assets/2162824/7064692/7fda68e6-deb9-11e4-8a0a-7120dfee28de.png)

Немножко не понимаю, зачем эта дата, если по умолчанию все кампании будут проводить сканирование каждый день(за исключением приостановленных)?
На старой версии тоже такое есть. При этом почему то с разными датами последнего сканирования, хотя кампании о которых я говорю - активны.

**Comment by alexzaporozhets** [comment]
@orestx  требует доп. обсуждения

**Comment by alexzaporozhets** [comment]
@orestx требует доп. обсуждения
