### ISSUE TITLE
progress bar  и ETA

### ISSUE THREAD

**Issue by maximsheiko** [startup-erector/website#39]

**Comment by orestx** [comment]
![image](https://cloud.githubusercontent.com/assets/2162824/7133800/7de992de-e29f-11e4-9bfa-571ca7a17223.png)

![image](https://cloud.githubusercontent.com/assets/2162824/7133834/d62ef06a-e29f-11e4-8bbf-a84c4b5716a8.png)

![image](https://cloud.githubusercontent.com/assets/2162824/7133870/3995d1a0-e2a0-11e4-89cd-7d6daa7a4d8e.png)

При одинаковых условиях шкала прогресса бывает разных цветов. При этом даже одна и та же шкала, в зависимости от ее настроения - то зеленая, то серая. Почему так?

**Comment by orestx** [comment]
Еще нюанс - по поводу того что шкала слетает на 1% после того как пройдет первый круг до 99%(или 100, хз)
Вот пример, это идет уже по новому кругу:
![image](https://cloud.githubusercontent.com/assets/2162824/7346780/6a01960e-ecea-11e4-892b-06f96c95fd24.png)
Было 23 лида на первом проценте второго круга, и вот:
![image](https://cloud.githubusercontent.com/assets/2162824/7346801/962177a4-ecea-11e4-9e3e-fc1257d5e043.png)
36 лидов все еще на первом проценте второго круга.
А всего в том "рейде" было найдено 40 лидов, если не ошибаюсь, оно так на первом или втором проценте второго круга так и закончило. Явно что то не так..

Плюс еще одно пожелание, но оно не высокого приоритета.. Шкала в процессе жизни с первого по девятый процент проходит цикл от серого по зеленый, потом где то с 10 по 100 проходит тот же цикл но медленнее.. В идеале, по моему, просто должно стремиться к зеленому за один цикл.

**Comment by maximsheiko** [comment]
это баг из-за того что я в это время обновил проект

**Comment by orestx** [comment]
@maximsheiko ты не все прокомментировал о чем я писал. Что бы было реализовано тоже не вижу в приложении..
>Шкала в процессе жизни с первого по девятый процент проходит цикл от серого по зеленый, потом где то с 10 по 100 проходит тот же цикл но медленнее.. В идеале, по моему, просто должно стремиться к зеленому за один цикл.
Если не получится, например потому что это сторонний модуль, то пиши "не получится, потому что мы используем готовое решение", или "это потребует требует много усилий, и с учетом того что приоритет низкий, предлагаю отложить на период доработок после запуска". Но как нибудь комментируй, перед тем как отправлять мне на проверку. Как мне проверять то на что ты никак не отреагировал?

**Comment by maximsheiko** [comment]
прошу прощения,буду писать.
сделал стабильно зеленый прогресс бар,нормально будет? реализовать градиент от серого к зеленому не смогу,не знаю как

**Comment by orestx** [comment]
Давай пока оставим зеленый а там, если потребуется, вернемся к этому вопросу. Просто когда к 10% становилось зеленым, ложно сообщало что закончился какой то этап сканирования, например можно было подумать что на 10% закончило сканирование через google и потом пошел bing...
Насчет того что прыгало после 100% в начало еще позже потестирую. Предварительно - похоже что все норм.

**Comment by orestx** [comment]
@maximsheiko 
Я думал мы побороли ситуацию когда шкала идет по второму кругу..
Только что смотреть, и у меня снова после 100% появился 1% и на нем закончило.
Хотя при попытке повторить - не получилось. В общем хз как оно работает, но никуда не подевалось.
Искал только в гугле, было одно ключевое слово: "timedoctor.com.ua".

**Comment by maximsheiko** [comment]
ссылку на скан плс

**Comment by orestx** [comment]
Возможно этот:
http://www.startup-erector.com/scans/gShwxW6hgFqRCJoAA

Но, к сожалению, точно не могу сказать что это он, потому что я разное тестировал и так как тот скан не завис а просто прыгнул на первый процент, то не запоминал конкретно о каком речь..
Не хорошо что деплой оказывает такое влияния на приложение (вызывает баги), но это отдельная тема, тогда ок.
