### ISSUE TITLE
нужно запоминать, на какой вкладке пользователь остановился, и когда он возвращается - активировать именно ее

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#41]
Это касается вкладок по статусам ссылок (new, done, canceled, all), вкладок из группы "links, comments, stats" и т.д.

**Comment by orestx** [comment]
На какой вкладке я сейчас нахожусь?
![image](https://cloud.githubusercontent.com/assets/2162824/7391300/9eacb83a-ee88-11e4-8495-f5b0c10b532f.png)

**Comment by orestx** [comment]
Кажется мы можем запоминать для каждой кампании последнюю вкладку отдельно. Проверь на старом приложении как там было: http://social-bot.herokuapp.com/

**Comment by orestx** [comment]
Кнопки подсвечиваются не правильно. Всегда активно "All", хотя в этом случае я вижу список Canceled(only):
![image](https://cloud.githubusercontent.com/assets/2162824/8281291/04fbab2e-18ef-11e5-828f-a0f238e13b59.png)

**Comment by vladmokryi** [comment]
#123
