### ISSUE TITLE
Почему у нас в любом случае необходимо указать url настоящего сайта?

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#45]
Мы с сайта  берем только ключевые слова. В нашем приложении это касается "грубо говоря" половины пользователей. Теоретически - вторая половина может пользоваться нашими услугами что бы рекламировать что то за границами интернета.

Например я могу искать блоги где обсуждается продажа мёда в Полтаве, и предлагать там свой мёд по адресу ул. Октябрская 25, в магазине "Пасечник". У меня нет сайта и в этом случае он не является необходимостью. Но воспользоваться startup-erector'ом я не могу потому что от меня требуется "какой то там сайт".
Скорее всего таких людей будет меньше половины, потому что он скорее обратится в рекламное агенство и разместит свою рекламу на кольцевых автобусах, но тем не менее, стоит это обсудить, потому что каких то особых преимуществ при таком раскладе как есть я не вижу.

**Comment by chemfind** [comment]
согласен с орестом, у нас должна быть возможность выбора или "сайт" или набор ключевых слов без сайта
