### ISSUE TITLE
Возможность деактивировать кампанию

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#47]
Нужен чекбокс, которым можно деактивировать кампанию, и при потребности - снова активировать. Это должно делаться на странице редактирования/создания кампании.
Так же, этот статус нужно как то отображать на dashboard.
Можно вешать соответствующий ярлычок в графе Url.

**Comment by orestx** [comment]
Сейчас у меня все старые кампании в состоянии "не активен":
![image](https://cloud.githubusercontent.com/assets/2162824/7345573/9fc9d690-ecde-11e4-8769-89a523cd136e.png)

Получается все старые кампании что были стали не активными потому что в базе не было записи "active": "true" ? (или тапа того)
Нужно сделать миграцию что бы все кто создавался в период когда нельзя было управлять активностью, по умолчанию были активными. Человек заходит, а его проекты отключены по причине того что... мы ввели новую фичу.

**Comment by maximsheiko** [comment]
>в базе не было записи "active": "true"
да,поэтому

**Comment by maximsheiko** [comment]
сделал миграцию

**Comment by orestx** [comment]
При редактировании поле "страна" становится пустым.
![image](https://cloud.githubusercontent.com/assets/2162824/7391381/71abed0a-ee89-11e4-8128-b71e5ef7443e.png)

**Comment by alexzaporozhets** [comment]
@orestx на проверку

**Comment by orestx** [comment]
вродь норм
