### ISSUE TITLE
убрать с выдачи мусор (stat, stats)

### ISSUE THREAD

**Issue by chemfind** [startup-erector/website#48]
убрать с выдачи мусор (stat, stats) пример:
http://gpu.ua.clearwebstats.com/
http://www.sitetrail.com/start.cv.ua
http://vidido.ua.cutestat.com/

**Comment by alexzaporozhets** [comment]
Все ссылки на эти сайтах нужно отсекать после выдачи поисковой системой

**Comment by maximsheiko** [comment]
https://github.com/startup-erector/website/blob/master/server/methods.js#L10 fixed
