### ISSUE TITLE
Изменения в процессе регистрации и создания первой кампании

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#52]
1. Сканирование копируется в кампании пользователя при регистрации или просмотре ссылки со стартовой.

2. В бесплатном пакете доступны только 4 ссылки, но только после регистрации (для своей кампании). Информацию, про ссылки которые были использованы хранить в модели Scan.

3. На списке только домены 

При копировании кампании нужно сохранять старый ID скана в поле "parentScanId".
Если пользователь создавал кампанию (хранить ID в сессии) нужно активировать ее по умолчанию. Также нужно проверять на повторное копирование кампании со стартовой.

**Comment by maximsheiko** [comment]
давать возможность пользователю копировать сканы ,только при регистрации, или когда он логинится со скана - тоже?

**Comment by maximsheiko** [comment]
И еще вопрос, @alexzaporozhets , только домены для ссылок - давать только не зарегистрированным пользователями  или тем кто не оплатил тоже?

**Comment by orestx** [comment]
Время сканирования искажено. Показывает когда я скопировал кампанию в свою учетку а не когда она сканировалась.
![image](https://cloud.githubusercontent.com/assets/2162824/9003847/464dd04e-377a-11e5-8834-2e777e47ccef.png)

**Comment by orestx** [comment]
Думаю стоит добавить ограничение что бы статусы больше 4-х лидов тоже нельзя было менять пока не купишь тариф. Сейчас я могу менять их с dashboard.

**Comment by maximsheiko** [comment]
как ты можешь менять статусы ссылок с dashboard?

**Comment by orestx** [comment]
:laughing: 
Просмотрел 4 лида, на 5-м увидел сообщение что нужно купить подписку. Перешел на страницу тарифов. Выбрал тариф и оплату через liqpay. Не оплачивая ничего вернулся на сайт и могу дальше работать, остальные лиды разблокировались. Безопасность на высшем уровне блин.
@maximsheiko  как ты проверял? ты вообще проверял что заливал?

Хотя нет, немного не так... Мне не нужно было переходить на страницу liqpay. Достаточно просто нажать select на странице тарифов.

**Comment by orestx** [comment]
>как ты можешь менять статусы ссылок с dashboard?
не dashboard, на странице лидов

**Comment by orestx** [comment]
Если я создал скан на публичной странице, потом по его ссылке зарегистрировался - этот скан скопировался в мой кабинет, это ок. Но после этого я удалил тот скан из своего кабинета, вылогинился и попал на список публичных сканов. Дальше я снова перешел по скану которых был создан мной, и ссылкой внутри этого скана я залогинился (та же процедура что регистрация нового пользователя по нажатию на лид, но я залогинился тем логином что недавно создал). В итоге этот мой скан не скопировался, хотя у меня его уже нет потому что я его перед этим удалил.
Я так понимаю это связано с косяком в этом пункте: 
>Также нужно проверять на повторное копирование кампании со стартовой.

**Comment by maximsheiko** [comment]
нет,это связано с игнорированием моих вопросов:
https://github.com/startup-erector/website/issues/52#issuecomment-125948161

**Comment by maximsheiko** [comment]
пофиксил баг с оплатой

**Comment by orestx** [comment]
Если ты не знал ответа то почему задача стоит на проверку? Зачем ты, зная что не готово, даешь проверять? Хотя бы комментарий написал что мол все сделал кроме этого пункта.
Ты задачу перевел на меня и я решил что ты в slack или по телефону или по факсу получил ответы.

**Comment by orestx** [comment]
>давать возможность пользователю копировать сканы ,только при регистрации, или когда он логинится со скана - тоже?

Думаю, учитывая случай что я описал, стоит дать возможность копировать при логине. Почему бы и нет? Мы же разрешаем копировать при регистрации чужие сканы...

**Comment by maximsheiko** [comment]
вопрос был и к тебе тоже, так как все проигнорили - я посчитал этот вопрос неважным, и назначил на проверку

**Comment by orestx** [comment]
>И еще вопрос, @alexzaporozhets , только домены для ссылок - давать только не зарегистрированным пользователями или тем кто не оплатил тоже?

С одной стороны - тем кто не оплатил тоже не стоит давать, ведь для них есть ограничение в 4 лида. Но с другой стороны это сильно перегрёбисто получится. В общем хз.. Интересно как остальные считают..

**Comment by maximsheiko** [comment]
сделал копирование во время логина, убрал возможность менять статусы > 4

**Comment by orestx** [comment]
>убрал возможность менять статусы > 4

а я все равно могу:
![image](https://cloud.githubusercontent.com/assets/2162824/9031962/7c9c1e90-39c2-11e5-97e7-383d1e2d61bb.png)

**Comment by maximsheiko** [comment]
@orestx хм, ну да, а как сделать? что бы он при смене статуса эта ссылка добавлялась в "просмотренные"?

**Comment by orestx** [comment]
Это не исправлено:
>Время сканирования искажено. Показывает когда я скопировал кампанию в свою учетку а не когда она сканировалась.

![image](https://cloud.githubusercontent.com/assets/2162824/9032017/f5724ace-39c2-11e5-8b70-37d4c3bc2376.png)

 (в оригинале, на стартовой, эта кампания сканировалась 3 дня назад):
![image](https://cloud.githubusercontent.com/assets/2162824/9032043/1d08d0b2-39c3-11e5-9ab1-bbefc40581ff.png)

**Comment by orestx** [comment]
Ситуация необычная, но тем не менее она имеет место, несколько раз проверил. На этом скрине:
![image](https://cloud.githubusercontent.com/assets/2162824/9032300/e2b3952a-39c5-11e5-97cc-1a97bbbae1af.png)
Если по очереди, начиная с первого, переходить по лидам то могу видеть 5 вместо 4-х. Но если после просмотра 5-го иду в обратном порядке то 4-й из них (тот что на скрине со статусом cancel) уже отказывается грузить, мол система работает и он среди тех 5 получается 5-й лишний.

**Comment by orestx** [comment]
Почему ни один вариант не активирован?
![image](https://cloud.githubusercontent.com/assets/2162824/9032347/5e86c442-39c6-11e5-92d8-34130075450b.png)

**Comment by orestx** [comment]
Не могу оплатить биткоинами подписку, нажатие на кнопку не дает никакого эфекта, модальное окно оплаты (или еще что то) не появляется
![image](https://cloud.githubusercontent.com/assets/2162824/9032422/26f402f0-39c7-11e5-9498-1d2033fa1b0a.png)

**Comment by orestx** [comment]
>хм, ну да, а как сделать? что бы он при смене статуса эта ссылка добавлялась в "просмотренные"?

а что тогда ты сделал в пятницу, когда написал такой комментарий?
>убрал возможность менять статусы > 4

При изменении статуса из списка нужно что бы этот лид получал обозначение что он уже не девственный и значит он занял место одного из четырех разрашенных. Как ты это делаешь не знаю, вроде бы обсуждалось раньше. Да и как то уже работает для тех лидов которые я просмотрел обычным способом, нажатием на его заголовок.

**Comment by orestx** [comment]
Если считаешь что будет нехорошо если пользователь потыкает 4 раза статусы и закончится его "триал", и он так и не увидит толком функционала, то это неплохая мысль и стоит внимания. В таком случае мы могли бы для бесплатных пользователей отображать на странице списка лидов статусы,но не давать их менять находясь на списке. А когда оплатит тариф и пропадет ограничение на 4-ку то можно вернуть ему возможность править статус из списка. Но это нужно еще обсудить, а пока не решили то делай этот момент так что бы соответствовало поставленной задаче а не "никак".

**Comment by maximsheiko** [comment]
>Если по очереди, начиная с первого, переходить по лидам то могу видеть 5 вместо 4-х

не могу повторить

**Comment by maximsheiko** [comment]
>а что тогда ты сделал в пятницу, когда написал такой комментарий?
>а не "никак"

именно то что написал, возможность менять статусы для ссылок, которых нет в массиве ограничения, то что я не учел смену статуса ДО просмотра ссылки, не значит что я просто проигнорировал этот таск

**Comment by maximsheiko** [comment]
>Не могу оплатить биткоинами подписку 

какая то проблема с приложением, возвращает 401 ошибку, я там ничего не менял в последнее время, попробую разобраться

**Comment by orestx** [comment]
@maximsheiko Что с этим? https://github.com/startup-erector/website/issues/52#issuecomment-127144080

![image](https://cloud.githubusercontent.com/assets/2162824/9300521/8cc98934-44cf-11e5-83d2-64ef2392dc2e.png)

**Comment by maximsheiko** [comment]
при регистрации указывается подписка, а на старые данные сейчас сделаю миграцию

**Comment by orestx** [comment]
Почему 0?
![image](https://cloud.githubusercontent.com/assets/2162824/9847649/2252cf5a-5ae3-11e5-9a46-a007f4353bac.png)

Я мачо, эта кампания активна(видно на скрине выше), но не вижу таймера, когда будет следующее сканирование. Оно вообще будет?
![image](https://cloud.githubusercontent.com/assets/2162824/9847685/6288a612-5ae3-11e5-8cff-cae2ca7f870a.png)

После регистрации мы дарим не 3 месяца а 21 день.

**Comment by maximsheiko** [comment]
а как у тебя получилось на 21 зарегистрироваться?

**Comment by orestx** [comment]
у меня не получилось на 21, но должно так быть.

**Comment by maximsheiko** [comment]
ок, исправил
