### ISSUE TITLE
ограничение длинны url и поля keywords

### ISSUE THREAD

**Issue by chemfind** [startup-erector/website#54]
нужно ограничить длинну url и поле keywords

**Comment by orestx** [comment]
@maximsheiko  какие сейчас требования к длине? Как мне проверять не зная нормы?

**Comment by maximsheiko** [comment]
150 символов, я еще не исправил

**Comment by orestx** [comment]
>Ограничение длинны url и поля keywords
150 это длина url, а для keywords?

**Comment by maximsheiko** [comment]
а по keywords я даже не знаю, сделать 50?

**Comment by orestx** [comment]
ok, сейчас потестим

**Comment by orestx** [comment]
Сейчас получается максимальная разрешенная длина url 149 вместо 150. При этом если вместо url использовать имя то там проходит 150.
Это не критично, но блин... Если оставить то так и останется. Там криво, там не ровно.. В общем оставляю с низким приоритетом, как будешь что то другое делать то и тут поменяешь.

**Comment by orestx** [comment]
или даже лучше, тут закрываем а тут #82 напомню об этом.
