### ISSUE TITLE
замечания к таймеру

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#60]
![image](https://cloud.githubusercontent.com/assets/2162824/7390703/6288125a-ee83-11e4-83dc-c816a83ba397.png)

Нет пробела.
Там где секунд меньше чем 10 я предлагаю писать не 9 секунд, а 09. По моему это привычный формат для таймера.

**Comment by maximsheiko** [comment]
исправил

**Comment by orestx** [comment]
ok
