### ISSUE TITLE
сканирование зависло?

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#61]
15 минут наблюдаю такую картину:
![image](https://cloud.githubusercontent.com/assets/2162824/7391054/82fe3fde-ee86-11e4-82ea-30774a63dc59.png)

После обновления страницы вообще такое стало:
![image](https://cloud.githubusercontent.com/assets/2162824/7391070/a44e3ab8-ee86-11e4-86e7-3ac01e6e8284.png)

Выхожу на dashboard и обратно в эту кампанию - вижу то что на первом скрине (50%)

**Comment by alexzaporozhets** [comment]
Добавляй перезапуск по cron

**Comment by maximsheiko** [comment]
добавил перезапуск по крон каждые 20 минут

**Comment by orestx** [comment]
Моя попытка специально положить сканирование новым билдом на сервере не увенчалась успехом, поэтому проверить не имею возможности.
