### ISSUE TITLE
Мы пустую строку считаем как keyword?

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#62]
![image](https://cloud.githubusercontent.com/assets/2162824/7391117/0b5bea70-ee87-11e4-9dd8-f66d87c27a57.png)

**Comment by orestx** [comment]
Нажал clear all и добавил фразу - теперь у меня пишет что 0 слов
![image](https://cloud.githubusercontent.com/assets/2162824/7391157/6c0df962-ee87-11e4-9a2a-6e9f4ff33749.png)

**Comment by orestx** [comment]
После скрина, показанного выше, запустил сканирование и оно закончилось на 50%.
![image](https://cloud.githubusercontent.com/assets/2162824/7391194/c12128de-ee87-11e4-97fd-87c47669fbb1.png)

**Comment by maximsheiko** [comment]
подсчет количества слов и завершение на 50% исправил,а насчет пустой строки не знаю как делатЬ? по факту она является ключевым словом,но могу сделать это ошибкой и сказать пусть пользователь уберет?

**Comment by orestx** [comment]
Мы не можем сделать проверку, если keyword равно "пробел" - не считать?
Ну при отображении может и не так важно. Но важно что бы, если я начинаю сканирование с такими двумя ключевыми словами, пустая строка что бы отбрасывалась и сканировало не по двум фразам, одна из которых - пробел, а только по одному (ну или сколько будет нормальных).
Тоесть что бы этого не было:
![image](https://cloud.githubusercontent.com/assets/2162824/7831913/96dd94a8-0463-11e5-8c3a-7950eed854f5.png)

**Comment by orestx** [comment]
ok
