### ISSUE TITLE
+ Add competitor URL

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#64]
![seo_tools__software_and_articles_-_seo_site_checkup___seositecheckup_com](https://cloud.githubusercontent.com/assets/891472/7428453/8395892e-eff9-11e4-9dd4-9e66812aa697.png)
 - http://seositecheckup.com

Нам нужно давать возможность устанавливать до 10 конкурентов

**Comment by alexzaporozhets** [comment]
есть но бажный

**Comment by orestx** [comment]
Создаю кампанию, вижу такое (это норм):
![image](https://cloud.githubusercontent.com/assets/2162824/7794428/257f5288-02d3-11e5-9d5e-5a7c05551ed4.png)

Жму добавить конкурента (это норм):
![image](https://cloud.githubusercontent.com/assets/2162824/7794443/361553f4-02d3-11e5-9d74-c8d6f87e88b7.png)

Возвращаюсь на dashboard, а после этого снова перехожу на страницу создания кампании. Эти переходы делаю не путем переходов по истории браузера (стрелкой назад) а тыкая кнопки на сайте. Тоесть снова жму "New campaign" и вижу такое:
![image](https://cloud.githubusercontent.com/assets/2162824/7794474/76f6ab0c-02d3-11e5-84b1-0e0438c91c2b.png)
 Но должен видеть такое:
![image](https://cloud.githubusercontent.com/assets/2162824/7794485/917a6a22-02d3-11e5-844c-395657753c66.png)

Что бы увидеть такое, мне нужно перезагрузить страницу средствами браузера (ctrl-r). 
В общем смысл рассказа таков что нужно при входе на страницу создания "новой кампании" делать все по умолчанию, с ноля, а не так как я делал прошлый раз.

**Comment by orestx** [comment]
А где кнопка "Добавить ссылку на конкурента"? ;)
![image](https://cloud.githubusercontent.com/assets/2162824/7881495/4a96c0c4-060c-11e5-95e9-da372e4dee68.png)

В общем если добавить максимальное количество конкурентов, ссылка "добавить конкурента" пропадает. После этого я удалил все строчки конкурентов, а кнопка не появилась... Должна появляться сразу же у меня появляется право на +1 поле конкурента.

**Comment by orestx** [comment]
Сделай кнопку удалить url конкурента по центру
![image](https://cloud.githubusercontent.com/assets/2162824/7881707/95837698-060e-11e5-87b5-0b8fdff6de35.png)

**Comment by orestx** [comment]
На публичной части сайта эта кнопка вообще не работает
![image](https://cloud.githubusercontent.com/assets/2162824/7881946/50fa924c-0611-11e5-96d7-8c05f37cdf43.png)

**Comment by orestx** [comment]
Почему тут нет валидации введенного url?
![image](https://cloud.githubusercontent.com/assets/2162824/7882011/e53f5758-0611-11e5-86fb-8f4379d628ed.png)

**Comment by orestx** [comment]
Нормально:
![image](https://cloud.githubusercontent.com/assets/2162824/8000822/e601613a-0b67-11e5-9faf-5104ed92695a.png)

Баг:
![image](https://cloud.githubusercontent.com/assets/2162824/8000838/15f8d72e-0b68-11e5-8aec-cc6dd6a752bc.png)

Баг:
![image](https://cloud.githubusercontent.com/assets/2162824/8000873/707d82f8-0b68-11e5-8f75-83574a6ca3af.png)
*Нет ключевых слов конкурента. Я специально показал что у timedoctor.com.ua они есть.*

Баг:
![image](https://cloud.githubusercontent.com/assets/2162824/8001020/313e7ca8-0b6a-11e5-9f78-ce720431f8b5.png)
*пустое поле прошло валидацию*

Баг (кнопку анализировать нажал но ничего не произошло):
![image](https://cloud.githubusercontent.com/assets/2162824/8001120/378582b8-0b6b-11e5-9238-5af2f5f673fd.png)
*Это случилось так: при создании новой кампании с пустым полем нажал анализировать. Получил ошибку что поле пустое. Я тогда добавил поле конкурента. Заполнил поле для моего сайта. Нажал сканировать и получил ошибку что поле конкурента пустое. Я удалил пустое поле конкурента и нажал снова анализировать. Но тогда уже кнопка анализировать перестала работать. Не получаю ни ошибки ни ключевых слов, на вид как просто кнопка перестала реагировать. Но похоже что защита от пустого поля для сайта конкурента не обнулилась когда я удалил это поле.*

**Comment by orestx** [comment]
А предыдущие баги норм поправил.

**Comment by maximsheiko** [comment]
исправил

**Comment by orestx** [comment]
Баг с удалением пустого поля для сайта конкурента - исправлен.
Баг, при котором не отображались ключевые слова конкурента - исправлен.
Насчет запуска с пустым полем конкурента - пока что ничего не скажу, там как то не всегда срабатывало, со временем посмотрим.

Вот тебе новый квест:
![image](https://cloud.githubusercontent.com/assets/2162824/8001921/47441c98-0b73-11e5-801b-0c87164592df.png)

*При таком раскладе, как на скрине, нажимая кнопку "Get my report" ничего не происходит. А должна быть ошибка что ключевых слов больше чем положено. *

**Comment by maximsheiko** [comment]
А можешь на видео повторить? у меня ошибка всплывает всегда

**Comment by orestx** [comment]
Могу организовать воображаемые слайды)
Создать кампанию.
Заполняю поле как timedoctor.com.ua
Добавляю конкурента и с пустым конкурентом жму анализировать
Получил ошибку что пустое поле у конкурента.
Спрятал пустое поле конкурента и запустил анализ.
Получил анализом 7 слов. После этого добавил еще двоих конкурентов timedoctor.com.ua
Запустил анализ. 
Получил 21 слово и баг при котором при нажатии на кнопку get my record не отображается ошибка что слов больше нормы.

Возможно еще как то можно воспроизвести, хз.

**Comment by maximsheiko** [comment]
спасибо,исправил

**Comment by orestx** [comment]
у меня все равно работает описанная выше схема

**Comment by orestx** [comment]
вродь норм
