### ISSUE TITLE
Не указан никакой тип сервиса комментариев на сайте, который мы выбрали как подходящий

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#65]
![image](https://cloud.githubusercontent.com/assets/2162824/7510469/0e74fe26-f4a5-11e4-9bc0-6cb094208b78.png)
Вот номер сканирования: http://www.startup-erector.com/scans/LYsfxajSfJJNwcnou (но это не публичный скан)

**Comment by maximsheiko** [comment]
это De:comments (https://decomments.com/)
на них нет пока иконки валидной,поэтому пока так

**Comment by orestx** [comment]
а, тогда ок. Но к запуску нужно не забыть ее поставить или найти другое решение, пустая клетка никуда не годится. В общем ок. Оставляем задачу активной как напоминание об иконке
