### ISSUE TITLE
Поменять разделитель на стартовой

### ISSUE THREAD

**Issue by maximsheiko** [startup-erector/website#66]
https://slack-files.com/files-tmb/T0271DLHB-F04TZ7MHA-c8883b66d9/startup_erector__we_trigger_your_potential_clients_desires__720.png

**Comment by orestx** [comment]
сейчас разделитель другой, думаю проблема решена.

![image](https://cloud.githubusercontent.com/assets/2162824/12512280/099c2f3a-c120-11e5-8adf-a11f037b6941.png)
