### ISSUE TITLE
Подключить liqpay & coinbase

### ISSUE THREAD

**Issue by maximsheiko** [startup-erector/website#67]

**Comment by orestx** [comment]
Сделай так что бы при выборе тарифа (нажатие кнопки "select"), открывалось модальное окно, в котором будет список возможных способов оплаты тарифного плана. Сейчас у нас есть liqpay и BTC. И после этого, в зависимости от того, что пользователь выберет, на liqpay его отправит на страницу оплаты liqpay, а если выберет BTC, то появится модальное окно с coinbase (как сейчас).

**Comment by alexzaporozhets** [comment]
@orestx с тебя тексты и moqups

**Comment by alexzaporozhets** [comment]
liqpay не работает

**Comment by orestx** [comment]
У меня прошла оплата через LiqPay и тариф поменялся с Virgin на Macho.

**Comment by orestx** [comment]
http://ninjamock.com/s/ymutdz  (в общем нас интересует блок "Choose you payment system", остальное я для ориентации нарысовал, поэтому даже не доделал. Насколько я помню на встрече решили что этот блок будет появляться когда пользователь выбрал тариф и нажал на соответствующую кнопку)

**Comment by orestx** [comment]
![image](https://cloud.githubusercontent.com/assets/2162824/8613648/ea590146-26e9-11e5-898b-344d8c79dcfa.png)
- Your selected subscription нужно писать на строчку ниже, обычным текстом;
- Иконку LiqPay заменить на Visa/MasterCard;
- Ссылка на доп. информацию должна быть target=_blank;
- Наверное VISA/MasterCard будет смотреться лучше, давай попробуем заменить.


Что то типа этого:
![image](https://cloud.githubusercontent.com/assets/2162824/8613818/d33d861a-26eb-11e5-863e-4c96ecca2c37.png)
- В общем еще названия платежек должны быть ссылками и вести на оплату (так же как иконки);
- В этом примере возможно стоит заменить картинку Visa/MasterCard на такуж же но с прозрачным фоном вместо белого.

**Comment by orestx** [comment]
Не "прокручивает" вниз при нажатии на кнопку Select. 
Так же, я просил сделать прозрачный фон а не черный, но пусть уже будет, а там посмотрим... Что с прокруткой?

**Comment by maximsheiko** [comment]
насчет фона из векторных нашел только такую картинку, прокрутку сделал

**Comment by orestx** [comment]
о, гуд
