### ISSUE TITLE
Фильтр по ключевым словам

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#7]
Тут ярлычки, названы ключевыми словами, исполняют роль фильтров? Тоесть по нажатию на крестик скрываются результаты поиска, а после того как я нажму там плюсик, они опять отобразятся? Тогда возможно стоит заменить крестики на что то другое (например глаз). Или например убрать их полностью оставив только текст, при этом вместо "Keywords" написать "Filter" или "Click to hide" и т.д.
Еще неплохо бы добавить кнопки "hide all" & "show all"

![image](https://cloud.githubusercontent.com/assets/2162824/6778965/317d5296-d160-11e4-9414-3defc8b722ec.png)

**Comment by orestx** [comment]
Show all и Hide all попробуем изобразить так:
![image](https://cloud.githubusercontent.com/assets/2162824/7133441/292c15bc-e29c-11e4-961f-629ce24f392a.png)

**Comment by orestx** [comment]
Show all/Hide all работает, а как насчет замены крестиков другой иконкой?

**Comment by vladmokryi** [comment]
Крестики остались - они вызывают popup по блокировке по ключу
Show\hide - теперь иконка

**Comment by orestx** [comment]
ок
