### ISSUE TITLE
публичная кампания. Пишет что нашло больше чем 2к лидов но если посмотреть на них то отображается лишь несколько штук

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#71]
![image](https://cloud.githubusercontent.com/assets/2162824/7793903/9d32376a-02cd-11e5-91ea-69a3d921d107.png)

пишет что найдено 2+к сайтов, но когда захожу - вижу в списке 0; Но, если побуду кое какое время на странице этой кампании то время от времени появляются по 1 ссылке новые, и счетсчик найденных ссылок вместе с их появлением инкрементится. В общем непонятки какие то, как оно так?  Речь идет об этом скане, он на публичной стартовой: http://www.startup-erector.com/scans/a22opQQgk2hTSgDjt

**Comment by maximsheiko** [comment]
баг был из-за того что счетчик ссылок не обнулялся. исправил
