### ISSUE TITLE
Максимальное количество кампаний для одной учетной записи

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#72]
Что это такое? Жму создать новую кампанию, а ничего не происходит. Как я догадался, и потом увидел подтверждение в консоли браузера, дело в ограничении количества кампаний для учетки. Только как пользователю это понять? Нужно нормальное оповещение что превышен лимит по количеству созданных кампаний.
![image](https://cloud.githubusercontent.com/assets/2162824/7831637/337316ec-0461-11e5-8f65-da60995282e3.png)

**Comment by orestx** [comment]
Так же нужно сообщить сколько кампаний можно создавать. А то я одну удалил, но все равно создавать новые не могу.. Хз сколько еще удалять

**Comment by maximsheiko** [comment]
да,тут надо сделать уведомления

**Comment by maximsheiko** [comment]
Сделал уведомления,а насчет количества в тайтле же написано сколько со скольки создано

**Comment by orestx** [comment]
@alexzaporozhets  Предлагаю написать вместо "Campaign count error" что то типа "You have used allowed number of campaigns. Consider upgrading your subscription."

**Comment by orestx** [comment]
>в тайтле же написано сколько со скольки создано

А насчет этого, как понять что там сколько со скольки, а не счет моей любимой хокейной команды, с которым она закончила последний матч? - нужна подсказка, потому что не всегда понятно что это за циферки. В общем, как обычно, title с текстом "Used/Available campaigns". Возможно стоит добавить active (Used/Available active campaigns), но не знаю как у нас с этим, считается как то количество неактивных кампаний или нет.

И где пробел между campaigns и открывающейся скобкой?
![image](https://cloud.githubusercontent.com/assets/2162824/7854002/ad5d1fcc-051d-11e5-8b83-6c00bcfad5e4.png)
Думаю хорошо бы сделать этот счетчик кликабельным, как то так:
![image](https://cloud.githubusercontent.com/assets/2162824/7854098/d83eb9de-051e-11e5-87ad-cde609c66cc9.png)
Но тогда, возможно, синий цвет (потому что ссылка) будет портить вид. В таком случает можно или сделать исключение что бы там ссылка оставалась черной, или хз, лучше обсудить.

**Comment by alexzaporozhets** [comment]
@orestx проверяй

**Comment by orestx** [comment]
Эта надпись должна быть ссылкой и вести на страницу тарифов
![image](https://cloud.githubusercontent.com/assets/2162824/7877704/1b639cac-05e7-11e5-9ed1-1e5b8fbc049c.png)

**Comment by orestx** [comment]
ok
