### ISSUE TITLE
Все иконки черно-белые, а тут цветная...

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#74]
![image](https://cloud.githubusercontent.com/assets/2162824/7854192/c7202b82-051f-11e5-9410-3103133bf603.png)

**Comment by chemfind** [comment]
иконки нужно сделать в одном стиле

**Comment by chemfind** [comment]
цветная иконка cackle
![startup_erector__we_trigger_your_potential_clients_desires_](https://cloud.githubusercontent.com/assets/7547101/8350455/847ba264-1b2e-11e5-83da-0dfef6ae193d.jpg)

**Comment by vladmokryi** [comment]
#195 дубль, закрываю эту
