### ISSUE TITLE
Избранное для ссылок (по аналогии со Slack)

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#75]
[ ] - add to favourites
[ ] - filter by  favourites

**Comment by orestx** [comment]
Видео. Прыгает сортировка при выделении некоторых лидов в избранное:
https://slack-files.com/T0271DLHB-F055ASVAC-e0265cc8f9

**Comment by orestx** [comment]
![image](https://cloud.githubusercontent.com/assets/2162824/7954847/d3b571d4-09db-11e5-9de2-e2f23c691417.png)

Слово hide тут не совсем подходит. Нажимая на ту кнопку, я ожидаю один из вариантов, или что увижу все ссылки, которые не обозначены звездочкой, или что увижу список ссылок, который был до нажатия, только из него будут убраны те что отмечены звездой.

Но в нашем случае, реализовано так что нажатие на ту кнопку сделает действие, свойственное для "show all". Вот наше избранное после нажатия на кнопку hide starred:
![image](https://cloud.githubusercontent.com/assets/2162824/7954891/54a295b0-09dc-11e5-8bd4-06c11182dfb9.png)

**Comment by maximsheiko** [comment]
просто убрать hide?

**Comment by orestx** [comment]
Тут не все так просто. Простой вариант - сделать что бы эта ссылка не меняла текст, тоесть все время писало show starred. А в идеале, наша проблема в том что кнопки show all & hide all просто сбрасывают состояние всех фильтров, а show starred - тригер, который переключается между режимами фильтрации по избранному или нет. Поэтому тут нужно как то отображать оба состояния. Может писать favorite (или starred) и менять звездочку на пустую в зависимости от состояния, активный фильтр или нет?
 А вообще.. По моему тут не место этой кнопке. Может сделать звездочку в таблице как нормальный элемент, сделать ей обычную графу. А в шапке Разместить тоже звездочку, которая будет или пустая или полная, в зависимости от состояния этого фильтра.. Хотя в шапке можно сортировку по избранных сделать..
Сейчас сортировка не работает:
![image](https://cloud.githubusercontent.com/assets/2162824/7955191/e2f6449a-09de-11e5-9b38-90327564cb25.png)

А избранное включать/отключать тут (мне кажется это самый лучший вариант с тех что я назвал):
![image](https://cloud.githubusercontent.com/assets/2162824/7955232/4e1610c0-09df-11e5-9e98-a122094e9720.png)

Хотя, еще можно сделать, почти ничего не меняя. Только что бы при активировании избранного кнопка show starred пряталась и оставались только hide all & show all. Но таким образом мы лишаемся оповещения о включенной сортировке по избранному, да и лишаемся возможности вернуть состояние, которое было до включения сортировки по избранному.

В общем хз, @alexzaporozhets  @chemfind , что скажете?

**Comment by maximsheiko** [comment]
Cделал кнопку как на последнем скрине, остальное оставляю на обсуждение

**Comment by orestx** [comment]
Немного не так. Планировалось что звездечка по приоритету будет на уровень ниже чем кнопки All, new, canceled, done. Тоесть Смотришь все что canceled, и среди них только отмечены звездой.
Так же, визуально, имелось ввиду не в виде кнопки/вкладки а просто рядом с ними, тоесть так:
![image](https://cloud.githubusercontent.com/assets/2162824/7956512/f38ac2fe-09e8-11e5-81de-7bb79e1ba5e0.png)
И когда фильтр активирован то не пустая звездочка будет а желтая.

**Comment by orestx** [comment]
И title="Show only starred items" / title="Disable filter by starred items"

А тут:
![image](https://cloud.githubusercontent.com/assets/2162824/7956591/70f6b81a-09e9-11e5-85c9-d76bdda6792a.png)

при наведении на зведочку должно писать title="Add star" / title="Remove star".

**Comment by orestx** [comment]
Замечания по размещению кнопки и по title - норм. Но сортировка в таблице по избранному не корректно работает.
Если так:
>У меня не было ни одного элемента, добавленного в избранное. Я зашел на список лидов и отметил несколько из них звездой.

Сортировка будет работать нормально.

Если же у меня было несколько отмеченных, а я зашел и начал делать правки, то есть одни элементы добавлять, другие удалять.. Сортировка сломается и заработает корректно только после того как я обновлю страницу (ctrl-r или перейду куда то и вернусь).

**Comment by maximsheiko** [comment]
для сортировки я использую уже готовую библиотеку, и она походу не может обрабатывать реактивность метеора...в общем не знаю как это исправить

**Comment by orestx** [comment]
@alexzaporozhets  we need your help.  По моему эта ситуация "важноватая", без нее фича с избранным становится не полноценной.

**Comment by orestx** [comment]
Проблема решена.
