### ISSUE TITLE
Баг с всплывающими оповещениями в время открытого модального окна с комментариями

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#78]
![image](https://cloud.githubusercontent.com/assets/2162824/7958476/89416b4a-09f8-11e5-84dd-4b08aa42a36c.png)

Во первых, сообщение прячется за темную занавесь, созданную модальным окном.
Во вторых - во время появления сообщения о том что скопировано - панель с кнопками "done", "cancel"... заплывает под главную черную навигацию сайта.

В общем потыкай сам, сразу станет видно.

**Comment by maximsheiko** [comment]
я знаю про этот баг, просто отображать оповещения в модальном окне не получается -вылазят ошибки, можно просто делать рядом с текстом например зеленую надпись (сopied) без всплывающих подсказок?

**Comment by orestx** [comment]
может можно поменять уровни слоев, что бы сообщение было на слой выше чем занавес модального окна?

**Comment by maximsheiko** [comment]
там нужно указать место в шаблоне для всплывания этой подсказки, и если я устанавливаю шаблон модального окна, оно отображается не на черной области, а на сам текст налазить пытается,я попробую еще по другому,но хз..

**Comment by orestx** [comment]
Я имею ввиду что у всплывающего окна z-index:999
а у того слоя модального окна, что закрывает весь экран темным - z-index:1000 и у самого модального окна, которое мы видим с белым фоном - 1001
Если сделать так что бы у сообщения было например z-index:1010, то наши сообщения будут поверх модального окна, но тем не менее не должны никуда сдвинуться, просто поднимутся выше.

**Comment by maximsheiko** [comment]
попробую разобраться как это сделать

**Comment by maximsheiko** [comment]
сделал

**Comment by orestx** [comment]
Сделал, но половину. Ты снова не читаешь что я пишу.

>Во вторых - во время появления сообщения о том что скопировано - панель с кнопками "done", "cancel"... заплывает под главную черную навигацию сайта.
https://slack-files.com/T0271DLHB-F056KN0UZ-db2a7ec2ce
Но тут думаю не критично, если не получится быстро решить - переведем в доработки после запуска.

**Comment by maximsheiko** [comment]
баг в том что дергается наше меню с кнопками? 
или что оповещение немного налазит на менюшку?
если первое,то я исправил

**Comment by orestx** [comment]
То что налазит оповещение на меню - думаю норм. Я имел ввиду что дергается (заплывает под главную черную навигацию сайта).  Сейчас уже нормально.
