### ISSUE TITLE
Баг с кнопкой переключения статуса лида на странице списка лидов

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#80]
Перехожу в какую то кампанию на список лидов.
Сейчас я могу менять статусы лидов прямо с таблицы как и положено.
Но как только я воспользуюсь кнопками-фильтрами "new/done/canceled/all" - возможность менять статусы прямо в таблице пропадает.

Скрины:

1. Все ок.
![image](https://cloud.githubusercontent.com/assets/2162824/8001656/55218baa-0b70-11e5-9195-c329fcce07af.png)

2.  Кнопка №2 уже не жмется
![image](https://cloud.githubusercontent.com/assets/2162824/8001670/84285f82-0b70-11e5-9427-0c26c7893f8b.png)

**Comment by orestx** [comment]
Без того что бы вместо клика меню статусов вызывалось при наведении нельзя?

Ты хоть сам проверил что получилось?

![image](https://cloud.githubusercontent.com/assets/2162824/8002282/1a24cdc2-0b76-11e5-9547-3fadef850164.png)

Те записи для которых я поделал статус canceled такими не стали, а остались new, только название статуса перестало отображаться. При чем обновление страницы не исправило ситуацию, похоже что пустые статусы поехали в базу.

**Comment by maximsheiko** [comment]
>Без того что бы вместо клика меню статусов вызывалось при наведении

это старый баг, что бы работали выпадающие списки нужно их инициализировать при перерисовке таблицы, а я этого не умею делать, поэтому сделал simple dropdown который работает без js,а насчет пустых статусов, я проверял, хз почему так

**Comment by orestx** [comment]
Насчет выпадающих списков думаю стоит обсудить, но я считаю что по возможности лучше оживить вариант "как было, по нажатию", но не критично. Но вот то что статусы накрылись это важно.

По моим наблюдениям: кампания, которая сканировалась последний раз a day ago  - багнутая. А кампания что сканировалась 21 час назад и 15 минут назад - работают нормально. Но взял одну из отключенных, что явно больше суток не обновлялась - нормально меняются статусы. То есть дело ясное что дело темное. В общем у меня из 10 кампаний у 2 из них такой баг. При чем одна из них активна и вчера сканировалась а вторая отключена.

**Comment by maximsheiko** [comment]
ок, щас исправлю
и это не зависит от кампаний, в любой кампании попробуй поменять фильтр с All>New и получишь тот баг)

**Comment by orestx** [comment]
А, ну гуд)
ждемс

**Comment by orestx** [comment]
вродь норм

**Comment by orestx** [comment]
не работает. Теперь баг при котором не открывается меню статуса проявляется по нажатию hide all/show all. Выглядит будто мы не причину а симптомы лечим (бывает что по другому никак, но как в нашем случае не знаю).

**Comment by maximsheiko** [comment]
так и есть :(
