### ISSUE TITLE
Возможность указать название кампании, в случае, если я не использую сайт для сбора ключевых слов

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#82]
Сейчас, если создавать кампанию путем "I don't have a website", созданная кампания будет безымянной. Позже ей можно дать имя, путем редактирования. Но это не дело. Когда я жму кнопку что у меня нет сайта, нужно что бы поле для ввода адреса сайта трансформировалось в поле для ввода названия кампании(а кнопку "анализировать" скрывать). Или можно добавлять еще один text input, который будет находиться между ключевыми словами и блоком с кнопкой "Analyse". В нем написать placeholder="Enter campaign name here" и так же думаю стоит добавить label который будет говорить что это поле для названия кампании. В то же время, input[placeholder="Enter url here"] и кнопку Analyse можно сделать неактивными, что бы не сбивали с толку.

**Comment by orestx** [comment]
Хорошо, но теперь графа в таблице не может называться "URL":
![image](https://cloud.githubusercontent.com/assets/2162824/8179399/122d5614-141f-11e5-9dd7-d52f6f944b83.png)
Назови "Campaign name", все равно, даже если там указан сайт, мы его не юзаем как адрес сайта, потому что он использовался как сайт только для сбора ключевых слов в начале, а дальше используется только как имя.

И еще, почему  "leads found": "/3" (видно на скрине)?

Так же, не нужно разрешать создавать кампанию без имени/url. Поле не должно быть пустым как сейчас:
![image](https://cloud.githubusercontent.com/assets/2162824/8179510/c466ca0e-141f-11e5-94e0-cdfca83a98a6.png)

Правда, у нас там есть старые кампании, без имен. Нужно подумать что с ними сделаем. Как вариант - назвать их каким то стандартным именем, типа "Your campaign"

**Comment by orestx** [comment]
При редактировании кампании с пустым именем я не могу присвоить ей название которое не является доменным именем. Валидация ругается что нужно указать валидный url.
![image](https://cloud.githubusercontent.com/assets/2162824/8450888/8d53818c-1fe7-11e5-907e-b137419a8577.png)

Так же кнопка save scan должна называться save campaign или даже лучше будет просто save.

**Comment by orestx** [comment]
Во время редактирования кампании нам url уже вообще не нужен (или я что то упускаю?), так что не нужна проверка на валидность домена. Должна быть возможность указать обычное название.
![image](https://cloud.githubusercontent.com/assets/2162824/8694953/07a8d9a6-2aeb-11e5-813b-05a8c349c15b.png)

Блин, Макс, когда ты начнешь читать все что я тебе пишу а не половину??

>Так же кнопка save scan должна называться save campaign или даже лучше будет просто save.

**Comment by orestx** [comment]
Хорошо, вышеописанное исправлено.
Но тут еще такое дело..
![image](https://cloud.githubusercontent.com/assets/2162824/8717655/157fefea-2ba6-11e5-89d7-f0c2653f1efa.png)

**Comment by orestx** [comment]
Семён Семёныч.... :disappointed: 
Путем редактирования создал безымянную кампанию
![image](https://cloud.githubusercontent.com/assets/2162824/8746733/ff40ac8e-2c94-11e5-970f-c26135589223.png)

https://www.youtube.com/watch?v=4laH4zZgYvA

**Comment by maximsheiko** [comment]
я делал таску по ограничению длины, а потом переключился на что то другое..в общем исправил

**Comment by alexzaporozhets** [comment]
Нужно пропускать длинные ссылки (150 символов)

**Comment by orestx** [comment]
По длине имени есть еще одна задача: #54 (просто для инфы)

**Comment by orestx** [comment]
Невалидный url ложит систему создания новой кампании:
![image](https://cloud.githubusercontent.com/assets/2162824/8774559/5d68fa5a-2ee8-11e5-9bf4-c05a253eb54e.png)
Уже минут 5 вижу такую картину, при этом если выйти на /dashboard и вернуться то увижу то же самое. Что бы разглючить приходится перезагружать страницу.

**Comment by orestx** [comment]
Указал имя кампании больше нормы(163 символа) - получил безымянную кампанию
![image](https://cloud.githubusercontent.com/assets/2162824/8774682/7a88e25c-2ee9-11e5-9e4e-23b0e603fa5d.png)
У тебя такого не было?

**Comment by orestx** [comment]
Сейчас получается максимальная разрешенная длина url 149 вместо 150. При этом если вместо url использовать имя то там проходит 150.
Это не критично, но блин... Если оставить то так и останется. Там криво, там не ровно..

И еще такой нюансик. Если я выбираю имя кампании вместо url, то кнопка анализировать становится не активной. Зато кнопка добавить конкурента работает, но толку от нее нет так как она используется только при подборе ключевых слов, а это делается только кнопкой "Analyse", которая стала не активной. Короче я вижу несколько вариантов:
1. Оставить возможность анализировать если я указал конкурентов. Тоесть если я выбрал что нет сайта и добавляю первого конкурента - должна появляться новая кнопка анализировать:
![image](https://cloud.githubusercontent.com/assets/2162824/8820047/9144dfce-305a-11e5-96bb-f34424e3c576.png)
2. Деактивировать возможность добавлять конкурентов если сказал что у меня нет сайта.

Только, если не ошибаюсь, мы осознано решили конкурентов оставлять, получается нужна кнопка (1-й вариант).

----------------------------
Плюс еще пища для размышлений. Мне кажется что никому не будет понятно зачем там указывать конкурентов и что это будет за новая кнопка "анализировать". Если раньше, когда было обязательно указывать свой url, не так важно было понимает он или нет, была одна кнопка анализировать и ее приходилось жать что бы продолжить использование сервиса, то теперь становится несколько кнопок, потому что уже есть "Get my report". То есть нужно еще какие то более явные подсказки что с помощью адресов конкурентов ему будут подобраны ключевики.
Поэтому, как минимум, предлагаю кнопку что появится для конкурентов назвать не Analyse а например Find keywords.

**Comment by maximsheiko** [comment]
такой вариант сработает? потому что так как ты нарисовал - слишком проблематичный

**Comment by orestx** [comment]
1. 149 на 150 так и не исправил.
2. 

>такой вариант сработает? потому что так как ты нарисовал - слишком проблематичный

А в чем именно проблема?  По моему было бы намного лучше если бы кнопка находилась на уровне с полями, а так же, не нужно проверять валидность имени при подборе ключевиков на сайтах конкурентов, ведь мы еще не сохраняем. Подбор ключевых слов это отдельная бонусная услуга вдобавок к созданию кампании. Она должна только искать слова и имя кампании ее не интересует. Раньше нам было важно потому что юзали url сайта клиента. Тоесть по нажатию analyse нужна проверка, а find keywords - нет.
.

**Comment by maximsheiko** [comment]
1. исправлю
2. проблема в том что я в цикле формирую поля для competitor Url и не могу придумать логического решения при котором в первом поле кнопка выводится - а в остальных нет

насчет валидации понял, уберу

**Comment by orestx** [comment]
почти готова новая форма, думаю эта тема не актуальна...
