### ISSUE TITLE
Проблемы с кодировкой результатов

### ISSUE THREAD

**Issue by chemfind** [startup-erector/website#85]
![startup_erector__we_trigger_your_potential_clients_desires_](https://cloud.githubusercontent.com/assets/7547101/8249168/1bf85b78-1670-11e5-8f72-918a85ee43a1.jpg)
http://www.startup-erector.com/scans/aZB7E6acFTgWj7juG

**Comment by maximsheiko** [comment]
http://www.startup-erector.com/scans/GAKytmmD7CrvJ8yhh
крокозябр нет
