### ISSUE TITLE
Target URL сделать активным

### ISSUE THREAD

**Issue by chemfind** [startup-erector/website#86]
сделать активным Target URL (открывать в новом окне) ?
![startup_erector__we_trigger_your_potential_clients_desires_](https://cloud.githubusercontent.com/assets/7547101/8252264/1716f07a-168d-11e5-833c-7a1598a39512.jpg)

**Comment by orestx** [comment]
Чуууувааак...©
![image](https://cloud.githubusercontent.com/assets/2162824/8594056/14832c7a-2646-11e5-92b7-497060bd6735.png)

**Comment by alexzaporozhets** [comment]
также не харкордте домен в коде!

**Comment by maximsheiko** [comment]
ок, добавлю проверку

**Comment by vladmokryi** [comment]
Все работает, условие есть, наверное макс сразу и исправил
![image](https://cloud.githubusercontent.com/assets/13148141/8637251/a647a022-2890-11e5-8f36-9bee67b0d5c0.png)
![image](https://cloud.githubusercontent.com/assets/13148141/8637249/957cab0c-2890-11e5-946c-80961df7a8ec.png)

**Comment by orestx** [comment]
ok
