### ISSUE TITLE
Не слишком ли велики у нас аппетиты?

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#87]
Немного попользовался нашим приложением. Написал несколько сообщений, прошелся по кампаниям и вот что с памятью:
![image](https://cloud.githubusercontent.com/assets/2162824/8281347/a00e035a-18ef-11e5-83b3-795dadc3d509.png)

**Comment by alexzaporozhets** [comment]
@maximsheiko память течет, используй отладчик chrome

**Comment by orestx** [comment]
Могу даже так:
![image](https://cloud.githubusercontent.com/assets/2162824/8281418/7baf59b8-18f0-11e5-9a4b-989e0903caf5.png)

**Comment by orestx** [comment]
Память накапливается за каждый подгруженный iframe. Нужно как то выгружать мусор что подгружался сайтами, которые я грузил через фрейм. Чем больше сайтов подгружаю - тем больше утечка.

**Comment by orestx** [comment]
>Чем больше сайтов подгружаю - тем больше утечка.

имеется ввиду не одновременно подгружаю в нескольких вкладках или еще что то. Просто по очереди посещаю, как обычно должно быть в работе.  И даже при переходе на dashboard ничего не сбрасивается

**Comment by orestx** [comment]
Как то странно, время от времени часть памяти очищается, но так.. При кое-каком времени использования доходит до стабильных 600+ мб. 
@maximsheiko  Можешь на пальцах объяснить что было сделано для того что бы решить эту проблему?
