### ISSUE TITLE
We can not generate keywords on this site — предлагать добавлять вручную

### ISSUE THREAD

**Issue by chemfind** [startup-erector/website#88]
We can not generate keywords on this site — предлагать добавлять вручную
![startup_erector__we_trigger_your_potential_clients_desires_](https://cloud.githubusercontent.com/assets/7547101/8341272/6d03210a-1acc-11e5-8523-2e74eb7e7b80.jpg)

**Comment by orestx** [comment]
Сообщение предлагаю поменять на такое: 
`We cannot generate keywords from this website, please add them manually`
И тогда автоматически нажимать "I do not have a website" при этом автоматически заполняя имя кампании сайтом который пользователь вводил в поле для анализа.
И хорошо бы сразу курсор перенести на textarea для keywords:
![image](https://cloud.githubusercontent.com/assets/2162824/8718305/1b4e1496-2bac-11e5-8965-f9b0390adf1f.png)

**Comment by orestx** [comment]
верю на слово
