### ISSUE TITLE
Hot status для ссылок которые найдены при последнем сканировании

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#89]
Выделить зеленым SE & position

**Comment by maximsheiko** [comment]
нужно получить доступ к данным внутри таблицы, отпишись получится ли

**Comment by orestx** [comment]
Вы правда решили вот так выделять?
![image](https://cloud.githubusercontent.com/assets/2162824/8717491/c01d6358-2ba4-11e5-86e8-84455aead513.png)

Или все же так?
![image](https://cloud.githubusercontent.com/assets/2162824/8717519/ffa00468-2ba4-11e5-92aa-c4def637dbec.png)

Первый вариант мне кажется неприемлем.
Если так выделять как ты сделал то разве что всю строку и не таким жирным. Но я все же за то что бы просто ярлыки покрасить.

**Comment by orestx** [comment]
@alexzaporozhets @chemfind Что скажете?

**Comment by orestx** [comment]
или так, но я так уже предлагал и не поддержали
![image](https://cloud.githubusercontent.com/assets/2162824/8717830/80154444-2ba7-11e5-9812-9d15af09ba0b.png)

**Comment by maximsheiko** [comment]
>Вы правда решили вот так выделять
>Выделить зеленым SE & position

мне не сказали конкретно как выделить

**Comment by orestx** [comment]
Давай если сегодня не поступит новых комментариев то покрасим ярлыки в зеленый. Думаю это имелось ввиду.

**Comment by alexzaporozhets** [comment]
мне больше всего нравиться подсветка фона, но нужно еще уточнить у @chemfind

**Comment by maximsheiko** [comment]
сделал подсветкой фона, но на первом скане слишком навязчиво смотрится, когда все ссылки - зеленые
![image](https://cloud.githubusercontent.com/assets/10918691/8725722/79e34e22-2bde-11e5-9044-a892d9f23b41.png)

**Comment by alexzaporozhets** [comment]
давай как-то полегче подсветим

**Comment by maximsheiko** [comment]
а так?
![image](https://cloud.githubusercontent.com/assets/10918691/8749256/289bbd80-2ca9-11e5-8ad9-fc2ee0ff2d00.png)

**Comment by vladmokryi** [comment]
@alexzaporozhets @maximsheiko @orestx 
а если такие варинаты?
![image](https://cloud.githubusercontent.com/assets/13148141/8772910/ab8d060a-2ed8-11e5-88b3-f05a06f08f50.png)

**Comment by orestx** [comment]
Варианты что остались:
1.
![image](https://cloud.githubusercontent.com/assets/2162824/8773880/951ce6bc-2ee0-11e5-8c88-608a188156e7.png)


2.
![image](https://cloud.githubusercontent.com/assets/2162824/8773603/0d35439a-2ede-11e5-9451-6dbff010ea89.png)


3.
![image](https://cloud.githubusercontent.com/assets/2162824/8773819/1e089562-2ee0-11e5-8327-a116786e01ca.png)


4.
![image](https://cloud.githubusercontent.com/assets/2162824/8773619/3635f2d0-2ede-11e5-9dde-25d37c9767e4.png)

5.
![image](https://cloud.githubusercontent.com/assets/2162824/8773846/5850e1de-2ee0-11e5-91f2-87804ff4a534.png)

В финал я бы отправил № 3, 4, 5

**Comment by orestx** [comment]
вродь норм
