### ISSUE TITLE
Фильтр по поисковым системам (страница сканирования)

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#90]
google [x], bing [x]

**Comment by orestx** [comment]
@alexzaporozhets 
Разве мы его не сюда хотели перенести?
![image](https://cloud.githubusercontent.com/assets/2162824/8644553/98032dde-2948-11e5-9c14-fa2b5a71849c.png)

**Comment by alexzaporozhets** [comment]
Да, и сжать высоту шапки

**Comment by maximsheiko** [comment]
так норм?

**Comment by orestx** [comment]
Если мне только кажется что это расстояние увеличилось то норм.
![image](https://cloud.githubusercontent.com/assets/2162824/8687059/f5dfd0b8-2a94-11e5-8538-bb777a99ad07.png)
Хотя мне бы хотелось приблизить немного таблицу, например так:
![image](https://cloud.githubusercontent.com/assets/2162824/8687110/a4fbc2aa-2a95-11e5-8bf6-2553207ad492.png) 
Давай немного опустим и будет ок, а там чуть - что еще обсудим.

**Comment by maximsheiko** [comment]
а как ты ее так приблизил?) 
и там еще после country идет такой же пробел, его тоже убирать?
![image](https://cloud.githubusercontent.com/assets/10918691/8687237/d3a2ab22-2a96-11e5-8bef-d159358fc254.png)

**Comment by orestx** [comment]
Там эти части поделены на блоки, но думаю все же лучше убрать между Country тоже.
У меня так получилось, вродь норм смотрится, и сразу меньше все эти приборы места занимают:

![image](https://cloud.githubusercontent.com/assets/2162824/8691632/f9237872-2acd-11e5-9d7e-05250ea12308.png)

Я делал через devtools в хроме, то в моем случае проще)
Достигался такой эфект если для блока с таблицей сделать padding-top:0 или margin-top:0
Так же для блока с keywords padding-top:0 или margin-top: -1em
Мне кажется что лучше padding оставить, а править margin.

**Comment by orestx** [comment]
ok
