### ISSUE TITLE
Добавить возможность нового комментария в модальном popup (страница лида)

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#91]

**Comment by orestx** [comment]
![image](https://cloud.githubusercontent.com/assets/2162824/8519724/82d20162-23dd-11e5-8b54-686dd53b7207.png)
не нужно что бы кнопка "Копировать" обтекалась текстом.

------------------------------------------
![image](https://cloud.githubusercontent.com/assets/2162824/8519733/98437c4c-23dd-11e5-89e9-2a9a21c3785d.png)
сделай текстовое поле 100% по ширине и на 25% меньше по высоте чем сейчас. Кнопка пусть будет снизу слева под полем. 
"Add a comment"  - лучше Add new comment, потому что просто "добавить комментарий" можно понять двояко, мол хочу добавить коммент на сайте что подгружен в фрейме, а тут мы именно новый в базу добавляем.

**Comment by orestx** [comment]
Так же, если добавлять коммент через этот pop-up, нет никаких проверок. Должны быть все те же проверки как и в разделе комментарии.
![image](https://cloud.githubusercontent.com/assets/2162824/8519816/170ff276-23de-11e5-869d-31dbe0676e02.png)

**Comment by orestx** [comment]
@vladmokryi Только настраивая валидацию не нужно дублировать код.

**Comment by orestx** [comment]
Зачем кнопке копирования столько места?
![image](https://cloud.githubusercontent.com/assets/2162824/8694793/11b412b8-2aea-11e5-98a4-9fd484780b19.png)

Почему это не сделано?

>"Add a comment" - лучше Add new comment, потому что просто "добавить комментарий" можно понять двояко, мол хочу добавить коммент на сайте что подгружен в фрейме, а тут мы именно новый в базу добавляем.

**Comment by maximsheiko** [comment]
так норм?

**Comment by orestx** [comment]
Норм, но выровняй элементы по левому краю
![image](https://cloud.githubusercontent.com/assets/2162824/8696914/697642dc-2af9-11e5-87c4-fc817d34bf3a.png)

Сейчас у нас так:
![image](https://cloud.githubusercontent.com/assets/2162824/8696925/7d115b10-2af9-11e5-98d5-3130324fe0cf.png)

Блин, не норм..
Добавь 4 любых комментария, и тогда по очереди попробуй каждый из них скопировать.
Начиная от 1 до 3-х, чем старее комментарий, тем больше сообщений что он скопирован будет появляться за 1 клик. Например тут, один раз нажал и что получил:
![image](https://cloud.githubusercontent.com/assets/2162824/8697009/1847544a-2afa-11e5-87b3-abdebbe22d0e.png)

**Comment by maximsheiko** [comment]
такой же баг и в основном окне добавления..щас исправлю

**Comment by orestx** [comment]
теперь, если я скопирую одно сообщение а потом передумаю и скопирую через пол секунды второе - второе сообщение не появляется, а появится только если я подожду когда исчезнет первое и тогда нажму копировать снова. При этом, если я сделал такую операцию, что должен был видеть одновременно два сообщения, то перестает работать кнопка "Закрыть" (крестик вверху справа) на том единственном сообщении.
Ты просто жестко ограничил количество одновременных сообщений,  что ли? Кажется мне что это приложение скоро захлебнется в море костылей.

**Comment by orestx** [comment]
ok
