### ISSUE TITLE
Правки формы для указания ключевых слов при создании кампании

### ISSUE THREAD

**Issue by orestx** [startup-erector/website#94]
![image](https://cloud.githubusercontent.com/assets/2162824/8450174/da0317c4-1fe0-11e5-8f77-5d91f6f7be55.png)

Кнопка clear all не должна касаться textarea. Когда появляется ошибка про не заполненные ключевые слова - этот отступ появляется. Где то такой отступ нам и нужен.
![image](https://cloud.githubusercontent.com/assets/2162824/8450240/7d8f27e8-1fe1-11e5-8b42-4cc3abc5d690.png)

По поводу подсчета пустых строк. Можно сделать проверку что бы пустая строка могла быть только там где сейчас находится курсор. То есть или вписываешь в строку какой то keyword или не сможешь создать еще одну строку.

**Comment by orestx** [comment]
Не вижу ни результата ни комментариев по второму вопросу. И уже не впервые. Почему так??

**Comment by orestx** [comment]
Идея правильная. Только 
1. Эта проверка не работает при редактировании.
2. Счетчик не согласен что не хватает ключевых слов:
![image](https://cloud.githubusercontent.com/assets/2162824/8980481/b0932344-36b9-11e5-9071-4481d85bf97e.png)
3. Тут  у меня даже сохранились пустые (в базу может как отдельные элементы пустота не пошла но счетчик накручивается пустыми строками):
![image](https://cloud.githubusercontent.com/assets/2162824/8980568/5b339784-36ba-11e5-9d45-d7f0f266d8bc.png)
![image](https://cloud.githubusercontent.com/assets/2162824/8980578/6d098a72-36ba-11e5-87c9-c57c0334205b.png)

**Comment by maximsheiko** [comment]
исправить работу счетчика

**Comment by maximsheiko** [comment]
добавление новой не пустой строки

**Comment by maximsheiko** [comment]
не записывать в базу повторяющиеся ключевики

**Comment by vladmokryi** [comment]
ушли от textarea
