### ISSUE TITLE
Переделать сортировку для списка ссылок

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#98]
@maximsheiko детализируй задачу для Влада (@vladmokryi)

**Comment by alexzaporozhets** [comment]
![startup_erector__we_trigger_your_potential_clients_desires_](https://cloud.githubusercontent.com/assets/891472/8474260/8586f7ce-20b7-11e5-8bb3-dadfef31a9fd.png)

**Comment by alexzaporozhets** [comment]
@vladmokryi нужно убрать пагинацию

**Comment by orestx** [comment]
@alexzaporozhets @vladmokryi Вродь хотели при прокрутке подгружать.. Сейчас отображается все сразу.

**Comment by vladmokryi** [comment]
@orestx если не ошибаюсь отдельная таска была где-то

**Comment by orestx** [comment]
>если не ошибаюсь отдельная таска была где-то
не нахожу такой..

**Comment by orestx** [comment]
>не нахожу такой..

нашел. Ни на кого не оформлена просто.. ок.
