### ISSUE TITLE
Проверить ссылки в iframe

### ISSUE THREAD

**Issue by alexzaporozhets** [startup-erector/website#99]

**Comment by orestx** [comment]
@maximsheiko 
Как должно вести себя наше приложение в случае когда попадаю на запрет загрузки сайта в iframe?

**Comment by maximsheiko** [comment]
вот так
![image](https://cloud.githubusercontent.com/assets/10918691/8697483/f96e158c-2afd-11e5-9936-a81a6ef13023.png)

**Comment by orestx** [comment]
Давай так напишем: This site can be opened only in a new window

**Comment by orestx** [comment]
у меня такая ситуация:
![image](https://cloud.githubusercontent.com/assets/2162824/8697532/4f736bd0-2afe-11e5-9c3c-cb7278a0a9a2.png)

**Comment by orestx** [comment]
Как ведет себя наше приложение когда находит такие сайты?
Дело в том что этот сайт был найден старым сканированием. Ты что то в базу пишешь что бы знать что они с запретом? По моему нужно это "наживо" определять, потому что, чисто теоретически, ситуация может меняться со временем.

**Comment by maximsheiko** [comment]
да, пишу в базу. как "наживо" определять - не знаю

**Comment by maximsheiko** [comment]
вроде исправил

**Comment by orestx** [comment]
![image](https://cloud.githubusercontent.com/assets/2162824/8699457/4f625cd6-2b0e-11e5-9404-530318a588c3.png)

**Comment by maximsheiko** [comment]
![image](https://cloud.githubusercontent.com/assets/10918691/8699555/f8180a4c-2b0e-11e5-9ff7-c39d04b17445.png)

**Comment by maximsheiko** [comment]
ты открываешь старый сайт. миграция сделается во время ежедневной проверки. на новом сайте такой проблемы нет. "Наживо" проверять не знаю как, перенаправляю тогда на @alexzaporozhets  пусть скажет что делать

**Comment by orestx** [comment]
вроде бы норм
